import type { StubPageData, HomeCapacidade, HomeEspecialidade, HomeSolucao, CaseStub } from "./types";

export const stubData: Record<string, StubPageData> = {
  solucoes: {
    eyebrow: "SOLUTIONS",
    title: "Solutions that start with the challenge, not the catalog.",
    intro:
      "Creation combines strategy, management and operational capacity according to the context, the moment and the structure of each project.",
    lead: "We can take on a specific front or connect the whole journey, from initial understanding to delivery and results analysis.",
    blocks: [
      {
        type: "cards",
        heading: "Start with what needs to happen",
        intro: "You don't need to know consulting vocabulary to find the right solution. The starting point is recognizing what's keeping the project from moving forward.",
        items: [
          { title: "I need to understand and decide", description: "Market intelligence, research, diagnosis, planning and prioritization." },
          { title: "I need to structure and make it viable", description: "Project structuring, modeling, resource planning and viability strategy." },
          { title: "I need to organize and manage", description: "Project management and PMO, process management, governance, KPIs and team coordination." },
          { title: "I need to execute and operate", description: "Event management, executive production, location services, fixer, ground transport and rentals." },
          { title: "I need to mobilize people and audiences", description: "Innovation, impact programs, cause marketing, branding, activations and experiences." },
          { title: "I need to measure and demonstrate", description: "Indicator design, data governance, evaluation, reports and measurement of impact or events." },
        ],
      },
      {
        type: "bullets",
        heading: "Different ways to work with us",
        items: [
          "Integrated project — Creation connects strategy, management and operation and answers for the complete journey defined in the contract.",
          "Specific front — we take on a delimited stage or competency, integrated into the client's existing structure.",
          "Team extension — we add temporary management, production or coordination capacity to internal teams, agencies and production companies.",
        ],
      },
    ],
    childrenLabel: "Capabilities and specialties",
    children: [
      { title: "Strategy", description: "Clarity to decide: market intelligence, diagnosis and planning, project structuring and viability.", href: "/solucoes/estrategia" },
      { title: "Management", description: "Rhythm to move forward: project management and PMO, business processes, governance and KPIs.", href: "/solucoes/gestao" },
      { title: "Operations", description: "Execution to deliver: event management, executive production, location & fixer, ground transport and logistics.", href: "/operacoes" },
      { title: "Innovation", description: "Projects, programs, hackathons and journeys that turn challenges into applicable solutions.", href: "/inovacao" },
      { title: "Impact", description: "Social responsibility programs, territorial development and results measurement.", href: "/impacto" },
      { title: "Branding & Experiences", description: "Brand strategy, narrative, activations and experiences that connect positioning and presence.", href: "/branding-experiencias" },
      { title: "Creation Ops Rio", description: "Integrated local operation in Rio de Janeiro for agencies, production companies, brands and international teams.", href: "/creator-ops-rio" },
    ],
    ctaLabel: "Tell us about your project",
    ctaHref: "/contato",
  },

  estrategia: {
    eyebrow: "STRATEGY",
    title: "Clarity before action.",
    intro: "We investigate the context, organize information and structure the choices that let the project move forward with direction.",
    lead: "For Creation, strategy is not a document isolated from execution. It's the definition of what needs to happen, why that path makes sense, and which conditions will make it possible.",
    parentLabel: "Solutions",
    parentHref: "/solucoes",
    blocks: [
      { type: "bullets", heading: "When Strategy is the entry point", items: [
        "There's an opportunity, but no structured decision yet.",
        "There's a lot of information and opinions, but no shared reading of the situation.",
        "The organization needs to understand its market, audience or competition.",
        "An idea needs to become a viable project.",
        "The investment is significant and the assumptions are still fragile.",
        "Different areas need to agree on objective, priority and path.",
        "A project has stalled and the problem needs to be revisited before accelerating again.",
      ]},
      { type: "bullets", heading: "Possible deliverables", intro: "Depending on scope, the Strategy front can produce:", items: [
        "Research and intelligence report.",
        "Organizational, market or project diagnosis.",
        "Scenarios and decision criteria.",
        "Audience and stakeholder definition.",
        "Value proposition or positioning thesis.",
        "Objectives, priorities and roadmap.",
        "Initial project model.",
        "Action plan.",
        "Risk and assumption map.",
        "Executive presentation for decision-making.",
      ]},
      { type: "bullets", heading: "Where this capability is applied", intro: "Strategy can be mobilized in projects across:", items: [
        "Innovation.",
        "Social responsibility and impact.",
        "Branding and experiences.",
        "Events and activations.",
        "SME expansion.",
        "Creative economy.",
        "Process and organizational transformation.",
        "Territorial projects.",
      ]},
    ],
    childrenLabel: "What we can take on",
    children: [
      { title: "Market Intelligence", description: "Research and analysis to understand market, competition, audiences, trends, risks and opportunities before deciding.", href: "/solucoes/inteligencia-de-mercado" },
      { title: "Diagnosis and Planning", description: "Structured reading of the current situation, problem definition, priorities, objectives and action plan.", href: "/solucoes/diagnostico-e-planejamento" },
      { title: "Project Structuring and Viability", description: "Turning an intention into scope, governance, budget, timeline, KPIs and resource strategy.", href: "/solucoes/estruturacao-de-projetos" },
    ],
    ctaLabel: "Talk about your challenge",
    ctaHref: "/contato",
  },

  "inteligencia-de-mercado": {
    eyebrow: "MARKET INTELLIGENCE",
    title: "Deciding better starts with understanding the real market.",
    intro: "Internal opinions, trends and isolated data don't form a strategy. Market intelligence connects evidence to answer specific questions about demand, competition, audiences, context and opportunity.",
    lead: "The work starts with the decision that needs to be made. Research is designed to reduce useful uncertainty, not to accumulate information.",
    parentLabel: "Strategy",
    parentHref: "/solucoes/estrategia",
    blocks: [
      { type: "bullets", heading: "When to hire Market Intelligence", items: [
        "Before launching a product, service, program or event.",
        "When entering a new territory, audience or segment.",
        "When competition has changed and the organization's position lost clarity.",
        "To evaluate an opportunity before investing significant resources.",
        "When internal decisions are based on conflicting perceptions.",
        "To understand the behavior, needs and barriers of an audience.",
        "Before redefining positioning, portfolio or value proposition.",
      ]},
      { type: "cards", heading: "Possible scope", items: [
        { title: "Desk research and secondary data", description: "Gathering studies, public databases, documents, industry reports and available information." },
        { title: "Benchmarking and competition", description: "Mapping references, offerings, business models, messaging, experiences and competitive moves." },
        { title: "Audiences and demand", description: "Interviews, surveys, qualitative listening, journey analysis and needs research." },
        { title: "Trends and scenarios", description: "Identifying forces of change, emerging signals, risks and possible consequences for the decision." },
        { title: "Territorial context", description: "Reading local actors, infrastructure, dynamics, opportunities and constraints of the territory." },
        { title: "Strategic synthesis", description: "Organizing evidence into implications, options and practical recommendations." },
      ]},
      { type: "bullets", heading: "What you get", intro: "The format depends on the question, but may include:", items: [
        "Research plan.",
        "Market or ecosystem map.",
        "Competitor and reference analysis.",
        "Audience profiles or segments.",
        "Interview and field research synthesis.",
        "Trends with implications for the business.",
        "Scenarios and decision criteria.",
        "Prioritized opportunities.",
        "Recommendations and next tests.",
        "Report and executive presentation.",
      ]},
      { type: "steps", heading: "How we conduct it", items: [
        { number: "01", title: "Defining the decision", description: "We align what needs to be decided, by whom and by when." },
        { number: "02", title: "Research design", description: "We choose sources, methods, sample, depth and criteria compatible with the decision and budget." },
        { number: "03", title: "Collection and analysis", description: "We gather data, identify patterns and document limitations." },
        { number: "04", title: "Interpretation", description: "We translate evidence into implications, hypotheses and options." },
        { number: "05", title: "Recommendation", description: "We present what the data allows us to conclude, what remains uncertain, and which next steps reduce risk." },
      ]},
      { type: "bullets", heading: "Who it's for", items: [
        "SMEs evaluating expansion or a new offering.",
        "Innovation, strategy and marketing teams.",
        "Institutes and social responsibility areas.",
        "Creators and creative economy businesses.",
        "Agencies and production companies preparing projects for clients.",
        "Organizations that need to understand a territory before acting.",
      ]},
    ],
    ctaLabel: "Bring us your business question",
    ctaHref: "/contato",
  },

  "diagnostico-e-planejamento": {
    eyebrow: "DIAGNOSIS AND PLANNING",
    title: "Before the plan, the right problem.",
    intro: "Planning too early can organize the wrong answer. Diagnosis clarifies what's happening, why it matters and what conditions need to change.",
    lead: "Planning turns that reading into priorities, actions, owners and follow-up criteria.",
    parentLabel: "Strategy",
    parentHref: "/solucoes/estrategia",
    blocks: [
      { type: "bullets", heading: "Signs that diagnosis is needed", items: [
        "The initial request describes a solution, but the problem still isn't clear.",
        "Each area presents a different reading of the situation.",
        "There are too many initiatives and not enough priorities.",
        "The project has lost momentum and no one can point to a single cause.",
        "Goals were set without connection to capacity, resources or audience.",
        "An important change needs to be rolled out, but there's no shared plan yet.",
      ]},
      { type: "steps", heading: "From diagnosis to plan", items: [
        { number: "01", title: "Framing", description: "We define the central question, the audiences involved and the expected use of the work." },
        { number: "02", title: "Listening and collection", description: "We analyze documents, data and the experiences of relevant people." },
        { number: "03", title: "Synthesis", description: "We identify causes, patterns, tensions, gaps and opportunities." },
        { number: "04", title: "Prioritization", description: "We compare themes by impact, urgency, feasibility and dependencies." },
        { number: "05", title: "Planning", description: "We turn priorities into objectives, initiatives, owners, deadlines, resources and KPIs." },
      ]},
      { type: "bullets", heading: "Possible deliverables", items: [
        "Executive diagnosis.",
        "Cause-and-effect map.",
        "Stakeholder analysis.",
        "Priority matrix.",
        "Definition of objectives and expected results.",
        "Implementation roadmap.",
        "Action plan with owners and deadlines.",
        "Risk and dependency map.",
        "Initial indicator system.",
      ]},
      { type: "bullets", heading: "Frequent applications", items: [
        "Planning new projects.",
        "Reviewing stalled initiatives.",
        "Preparing impact programs.",
        "Organizing areas or work fronts.",
        "Planning complex events and experiences.",
        "Designing innovation programs.",
      ]},
    ],
    ctaLabel: "Talk about the context",
    ctaHref: "/contato",
  },

  "estruturacao-de-projetos": {
    eyebrow: "PROJECT STRUCTURING AND VIABILITY",
    title: "An idea only becomes a project when it can be executed.",
    intro: "We structure initiatives so they can be understood, decided on, financed, managed and realized.",
    lead: "That means turning intention into objectives, scope, deliverables, governance, resources, timeline, risks and KPIs that all fit together.",
    parentLabel: "Strategy",
    parentHref: "/solucoes/estrategia",
    blocks: [
      { type: "bullets", heading: "When an initiative still isn't a project", items: [
        "Broad objectives without defined deliverables.",
        "Audience or beneficiaries described generically.",
        "Budget with no calculation backup.",
        "Timeline with no dependencies or owners.",
        "Partners mentioned but not yet mobilized.",
        "Indicators that can't be measured.",
        "Fundraising expectations with no financing strategy.",
      ]},
      { type: "cards", heading: "What we structure", items: [
        { title: "Project logic", description: "Problem, rationale, objectives, audiences, expected results and the relationship between activities and deliverables." },
        { title: "Scope and deliverables", description: "What will be done, what's out of scope, how each deliverable will be accepted, and what dependencies exist." },
        { title: "Governance", description: "Roles, responsibilities, decision forums, partners and follow-up methods." },
        { title: "Delivery plan", description: "Stages, timeline, team, vendors, resources, risks and required operation." },
        { title: "Budget", description: "Cost categories, assumptions, quotes, reserves and the relationship between resources and activities." },
        { title: "Indicators", description: "How to track execution, reach, quality, results and learning." },
      ]},
      { type: "bullets", heading: "Possible deliverables", items: [
        "Structured project document.",
        "Logical framework or theory of change.",
        "Scope and work breakdown structure.",
        "Work plan.",
        "Timeline and milestones.",
        "Budget and calculation backup.",
        "Governance and stakeholder map.",
        "Risk matrix.",
        "Indicator plan.",
        "Partnership and resource strategy.",
        "Institutional or commercial presentation.",
      ]},
      { type: "steps", heading: "How we work", items: [
        { number: "01", title: "Understanding", description: "We gather what already exists and define the questions still without answers." },
        { number: "02", title: "Architecture", description: "We connect problem, objectives, audiences, activities, deliverables and results." },
        { number: "03", title: "Modeling", description: "We structure governance, timeline, resources, budget, risks and indicators." },
        { number: "04", title: "Validation", description: "We test coherence, execution capacity and fit with the decision process or financing mechanism." },
        { number: "05", title: "Preparation", description: "We consolidate documents, presentations and next steps for contracting, partnership or implementation." },
      ]},
      { type: "bullets", heading: "Projects we can structure", items: [
        "Corporate initiatives.",
        "Innovation programs.",
        "Cultural and creative economy projects.",
        "Social responsibility programs.",
        "Events and experiences.",
        "Territorial projects.",
        "Author-driven initiatives.",
        "Projects for direct contracting, sponsorship, public calls or incentive laws.",
      ]},
    ],
    ctaLabel: "Structure your project",
    ctaHref: "/contato",
  },

  gestao: {
    eyebrow: "MANAGEMENT",
    title: "The responsibility that doesn't get handed off.",
    intro: "A plan doesn't create momentum on its own. Projects move forward when decisions have owners, information flows, risks are handled and teams know what needs to happen next.",
    lead: "Creation structures and runs that management system, connecting strategy, people, processes and deliverables.",
    parentLabel: "Solutions",
    parentHref: "/solucoes",
    blocks: [
      { type: "bullets", heading: "When Management needs to step in", items: [
        "The project spans several areas and has no integration leadership.",
        "There are many meetings but few recorded decisions.",
        "Deadlines change without the impacts being understood.",
        "Teams and vendors are working from different versions of the plan.",
        "The client has technical knowledge but no available capacity to coordinate everything.",
        "Recurring problems point to process failures, not just lack of effort.",
      ]},
      { type: "bullets", heading: "Possible deliverables", items: [
        "Project plan.",
        "Governance structure.",
        "Responsibility matrix.",
        "Integrated timeline.",
        "Budget and cost control.",
        "Risk, issue and dependency map.",
        "Communication and stakeholder plan.",
        "Executive dashboards and reports.",
        "Processes and procedures.",
        "Closeout report and lessons learned.",
      ]},
    ],
    childrenLabel: "What we can take on",
    children: [
      { title: "Project Management and PMO", description: "Planning, governance, coordination, monitoring and closeout of projects or portfolios.", href: "/solucoes/gestao-de-projetos" },
      { title: "Business Process Management", description: "Mapping, redesigning and implementing processes to reduce dependency on people, rework and information loss.", href: "/solucoes/gestao-de-processos" },
      { title: "Governance and KPIs", description: "Roles, forums, decision criteria, indicators and routines that turn monitoring into action.", href: "/solucoes/governanca-e-indicadores" },
    ],
    ctaLabel: "Talk about managing your project",
    ctaHref: "/contato",
  },

  "gestao-de-projetos": {
    eyebrow: "PROJECT MANAGEMENT AND PMO",
    title: "Projects move forward when decisions have an owner.",
    intro: "We coordinate the system that connects objective, scope, teams, budget, deadline, risks and deliverables.",
    lead: "Management turns scattered information into visible decisions and keeps work moving until completion.",
    parentLabel: "Management",
    parentHref: "/solucoes/gestao",
    blocks: [
      { type: "cards", heading: "Possible scope", items: [
        { title: "Initiation", description: "Objective, scope, deliverables, stakeholders, assumptions, constraints and success criteria." },
        { title: "Planning", description: "Timeline, budget, team, procurement, communication, risks, quality and indicators." },
        { title: "Governance", description: "Roles, forums, authority levels, cadence, records and escalation paths." },
        { title: "Coordination", description: "Following up on teams, partners, vendors, dependencies and decisions." },
        { title: "Control", description: "Monitoring deadline, cost, scope, risks, issues, changes and deliverables." },
        { title: "Closeout", description: "Acceptance, documentation, accountability, lessons learned and transition." },
      ]},
      { type: "cards", heading: "PMO sized to the context", intro: "A PMO doesn't have to mean a heavy or permanent structure.", items: [
        { title: "Project PMO", description: "Organizes governance, information and monitoring for a specific initiative." },
        { title: "Program PMO", description: "Coordinates related projects, shared benefits and dependencies across fronts." },
        { title: "Portfolio PMO", description: "Supports prioritization, capacity, indicators and decisions across multiple initiatives." },
        { title: "Temporary PMO", description: "Implements practices and runs management during a critical phase, preparing the handover to the internal team." },
      ]},
      { type: "bullets", heading: "What can be delivered", items: [
        "Charter or initiation document.",
        "Integrated project plan.",
        "Work breakdown structure and timeline.",
        "Responsibility matrix.",
        "Budget and commitment control.",
        "Stakeholder map.",
        "Risk and issue matrix.",
        "Executive dashboard.",
        "Status reports.",
        "Closeout and transition plan.",
      ]},
      { type: "bullets", heading: "Creation can step in at three moments", items: [
        "Before kickoff — to structure the project and prepare governance, plan and mobilization.",
        "During execution — to take on coordination, restore visibility and address blockers.",
        "In a critical phase — to reorganize a front, prepare an event, carry out an implementation or lead the closeout.",
      ]},
      { type: "bullets", heading: "Who it's for", items: [
        "SMEs with no dedicated internal project structure.",
        "Corporate areas leading cross-functional initiatives.",
        "Institutes and social organizations.",
        "Agencies and production companies that need additional coordination.",
        "Innovation, impact, events and creative economy programs.",
      ]},
    ],
    ctaLabel: "Tell us about your project",
    ctaHref: "/contato",
  },

  "gestao-de-processos": {
    eyebrow: "BUSINESS PROCESS MANAGEMENT",
    title: "The work needs to function beyond the people who sustain it.",
    intro: "When a process only exists in the memory of whoever runs it, the organization becomes vulnerable to delays, rework, information loss and inconsistent decisions.",
    lead: "We map how the work actually happens, redesign what needs to change, and follow the rollout until the new flow can be run by the team.",
    parentLabel: "Management",
    parentHref: "/solucoes/gestao",
    blocks: [
      { type: "bullets", heading: "Signs a process needs review", items: [
        "The same task is done differently by different people.",
        "Information has to be typed or double-checked multiple times.",
        "Approvals have no deadline, criteria or clear owner.",
        "The client or user doesn't know what stage they're at.",
        "The operation depends excessively on one person.",
        "Tools were rolled out without redesigning the workflow.",
      ]},
      { type: "steps", heading: "How we conduct it", items: [
        { number: "01", title: "Prioritize", description: "We choose the processes with the greatest effect on results, risk or experience." },
        { number: "02", title: "Understand", description: "We map the real flow, including the shortcuts and exceptions that rarely show up in manuals." },
        { number: "03", title: "Redesign", description: "We build the future process with input from both decision-makers and those who execute it." },
        { number: "04", title: "Implement", description: "We define owners, procedures, tools, training and transition." },
        { number: "05", title: "Follow up", description: "We measure adoption, fix gaps and prepare the team to run it independently." },
      ]},
      { type: "bullets", heading: "Possible deliverables", items: [
        "Process inventory.",
        "Current-state and future-state maps.",
        "BPMN diagrams when appropriate.",
        "Responsibility matrix.",
        "Bottleneck and risk analysis.",
        "Procedures and work instructions.",
        "Decision criteria and authority levels.",
        "Functional requirements for systems.",
        "Process indicators.",
        "Implementation plan.",
      ]},
      { type: "bullets", heading: "Frequent applications", items: [
        "Customer service and journey.",
        "Proposal drafting and approval.",
        "Procurement and vendor management.",
        "Event production.",
        "Project management.",
        "Social program operations.",
        "Content creation and publishing.",
        "Accountability reporting.",
      ]},
    ],
    ctaLabel: "Talk about your processes",
    ctaHref: "/contato",
  },

  "governanca-e-indicadores": {
    eyebrow: "GOVERNANCE AND KPIS",
    title: "Decision, responsibility and evidence in the same system.",
    intro: "Governance defines who decides, based on what information and within what limits. Indicators show what needs attention.",
    lead: "When the two are disconnected, reports pile up and problems remain without an owner. We structure the system that links information to decision and decision to follow-up.",
    parentLabel: "Management",
    parentHref: "/solucoes/gestao",
    blocks: [
      { type: "cards", heading: "What we structure", items: [
        { title: "Governance architecture", description: "Roles, responsibilities, forums, authority levels, escalation and the relationship between instances." },
        { title: "Decision matrix", description: "Who recommends, approves, executes, consults and follows up on each relevant topic." },
        { title: "Management cadence", description: "Meetings, rituals, agendas, preparation, records and decision follow-up." },
        { title: "Indicator system", description: "Objectives, management questions, metrics, formulas, sources, frequency and owners." },
        { title: "Dashboards and reports", description: "Visualizations and summaries suited to who operates, manages or sponsors." },
        { title: "Accountability", description: "Organizing evidence, deliverables, results, risks, deviations and learnings." },
      ]},
      { type: "bullets", heading: "Possible deliverables", items: [
        "Governance map.",
        "RACI matrix or equivalent.",
        "Forum and committee charter.",
        "Authority-level matrix.",
        "Management calendar.",
        "Indicator tree or catalog.",
        "Metric fact sheets.",
        "Dashboard template.",
        "Executive report template.",
        "Implementation and adoption plan.",
      ]},
      { type: "bullets", heading: "Different levels of evidence", intro: "We distinguish activity, output, reach, result and impact — so that volume of activity is never presented as proven transformation.", items: [
        "Activity: what was done.",
        "Output: what was produced.",
        "Reach: who was involved.",
        "Result: what changed in an observable way.",
        "Impact: change attributable or plausibly related, according to available method and evidence.",
      ]},
      { type: "bullets", heading: "For projects, programs and operations", items: [
        "Corporate projects.",
        "Social responsibility programs.",
        "Portfolios and PMOs.",
        "Social organizations.",
        "Events and experiences.",
        "Recurring processes.",
        "Innovation initiatives.",
        "Partnerships with multiple stakeholders.",
      ]},
    ],
    ctaLabel: "Talk about your governance",
    ctaHref: "/contato",
  },

  operacoes: {
    eyebrow: "OPERATIONS",
    title: "Execution is where the project gets decided.",
    intro: "A good plan needs to work within real time, budget and territory. Creation coordinates people, vendors, resources, permits, travel and decisions so every front moves forward clearly to delivery.",
    lead: "We act as the operational core or as an extension of the client's team, with defined responsibility and close follow-up.",
    parentLabel: "Solutions",
    parentHref: "/solucoes",
    blocks: [
      { type: "bullets", heading: "What we coordinate", items: [
        "Operational scope and delivery criteria.",
        "Budget, contracting and cost control.",
        "Timeline, milestones and sequencing.",
        "Vendors, technical teams and partners.",
        "Infrastructure, equipment and materials.",
        "Permits, authorizations and local requirements.",
        "Logistics for people, cargo and resources.",
        "Contingencies, changes and field communication.",
      ]},
      { type: "bullets", heading: "Where we plug in", intro: "Creation can take on the whole operation or a delimited front. We can also integrate into existing structures, including:", items: [
        "Marketing and communications teams.",
        "Production companies and agencies.",
        "Social responsibility and sustainability areas.",
        "Cultural and social organizations.",
        "Audiovisual production companies.",
        "Brands, creators and independent projects.",
      ]},
    ],
    childrenLabel: "Our fronts of work",
    children: [
      { title: "Event Management", description: "Planning and coordinating the full cycle of corporate, cultural, institutional, innovation and impact events.", href: "/operacoes/gestao-de-eventos" },
      { title: "Executive Production", description: "Budget, timeline, vendors, teams, infrastructure and follow-up from pre-production to closeout.", href: "/operacoes/producao-executiva" },
      { title: "Location & Fixer", description: "Location research, local liaison, permits, team support and production troubleshooting in Rio de Janeiro and the Costa Verde.", href: "/operacoes/location-fixer-rio-de-janeiro" },
      { title: "Ground Transport, Drivers & Rentals", description: "Travel, vehicles, drivers, lodging, spaces, equipment and arrival support for teams, guests and productions.", href: "/operacoes/receptivo-drivers-locacoes" },
    ],
    ctaLabel: "Tell us about your operation",
    ctaHref: "/contato",
  },

  "gestao-de-eventos": {
    eyebrow: "EVENT MANAGEMENT",
    title: "An event starts long before setup.",
    intro: "Objective, audience, experience, content, budget and operation all need to point in the same direction.",
    lead: "Creation structures and coordinates events from concept to closeout, connecting strategic decisions with execution.",
    parentLabel: "Operations",
    parentHref: "/operacoes",
    blocks: [
      { type: "steps", heading: "The full cycle", items: [
        { number: "01", title: "Concept and objectives", description: "Defining the event's role, audiences, value proposition, expected results and success criteria." },
        { number: "02", title: "Experience architecture", description: "Format, program, attendee journey, environments, flows, activations and touchpoints." },
        { number: "03", title: "Planning", description: "Scope, budget, timeline, governance, vendors, risks, permits and operational plan." },
        { number: "04", title: "Production", description: "Infrastructure, audiovisual, set design, catering, teams, materials, logistics, setup and testing." },
        { number: "05", title: "Execution and closeout", description: "Overall coordination, stage or floor operation, teardown, reconciliation, data and report." },
      ]},
      { type: "bullets", heading: "Events we can structure and run", items: [
        "Corporate and institutional gatherings.",
        "Conferences, forums and seminars.",
        "Hackathons and innovation programs.",
        "Cultural and creative economy events.",
        "Brand activations and live marketing.",
        "Social responsibility and impact events.",
        "Live broadcasts and hybrid formats.",
      ]},
      { type: "bullets", heading: "Possible deliverables", items: [
        "Event concept and design.",
        "Master plan and timeline.",
        "Budget and contracting map.",
        "Responsibility matrix.",
        "Program and technical run-of-show.",
        "Space, flow and access plan.",
        "Risk and contingency plan.",
        "Check-in operation.",
        "Execution report and indicators.",
      ]},
    ],
    ctaLabel: "Plan your event",
    ctaHref: "/contato",
  },

  "producao-executiva": {
    eyebrow: "EXECUTIVE PRODUCTION",
    title: "Executive production is turning many dependencies into one delivery.",
    intro: "When a project needs to leave the page, every contract, deadline, access point and decision starts affecting the whole.",
    lead: "Creation organizes those dependencies and coordinates execution with an eye on budget, timeline, quality and risk.",
    parentLabel: "Operations",
    parentHref: "/operacoes",
    blocks: [
      { type: "bullets", heading: "Where we work", items: [
        "Corporate, cultural and institutional events.",
        "Brand campaigns and activations.",
        "Innovation and creative economy projects.",
        "Social and territorial programs.",
        "Filming, content and audiovisual production.",
        "Fairs, exhibitions and experiences.",
        "Special projects with multiple partners.",
      ]},
      { type: "cards", heading: "What executive production can include", items: [
        { title: "Production planning", description: "Scope breakdown, timeline, budget, resource map, work sequence and decision points." },
        { title: "Budgets and contracting", description: "Requesting and comparing proposals, technical and commercial equalization, contracting support and commitment control." },
        { title: "Vendors and teams", description: "Selection, briefing, integration, follow-up, deliverable validation and interface management." },
        { title: "Infrastructure and logistics", description: "Spaces, equipment, materials, transport, lodging, catering, access, cargo and returns." },
        { title: "Permits and requirements", description: "Mapping authorizations, documents, insurance and applicable technical responsibilities." },
        { title: "Field operation", description: "Setup, testing, run-through, execution, teardown, incident control and communication across fronts." },
      ]},
      { type: "bullets", heading: "Controls that sustain delivery", items: [
        "Base budget and closing projection.",
        "Production timeline.",
        "Vendor and contract map.",
        "Responsibility matrix.",
        "Approval and change control.",
        "Equipment and materials list.",
        "Access and check-in plan.",
        "Risk and contingency map.",
        "Incident and closeout report.",
      ]},
      { type: "bullets", heading: "How we integrate with the team", items: [
        "Full production — Creation is responsible for planning and coordinating the whole set defined in the contract.",
        "Specific front — we take on a delimited part, such as logistics, vendors, local production or field operation.",
        "Temporary reinforcement — we come in as an extension of the agency, production company, brand or organization during a critical stage.",
      ]},
    ],
    ctaLabel: "Talk about your production",
    ctaHref: "/contato",
  },

  "location-fixer-rio-de-janeiro": {
    eyebrow: "LOCATION & FIXER",
    title: "You arrive with the project. The local operation already knows the way.",
    intro: "Locations, permits, access, teams and travel change from one territory to another.",
    lead: "Creation offers location research and local production support for teams shooting, running campaigns, events and projects in Rio de Janeiro and the Costa Verde.",
    parentLabel: "Operations",
    parentHref: "/operacoes",
    blocks: [
      { type: "cards", heading: "Two services that complement each other", items: [
        { title: "Location", description: "Research and viability of spaces compatible with the creative brief, technical needs, budget and production logistics." },
        { title: "Fixer", description: "Local liaison to turn a brief into a workable operation, connecting information, people, vendors, requirements and decisions on the ground." },
      ]},
      { type: "bullets", heading: "Location services", items: [
        "Reading the creative and technical brief.",
        "Initial research of options.",
        "In-person scouting, as scoped.",
        "Photos, videos and operational information.",
        "Analysis of access, noise, power, support and circulation.",
        "Liaison with owners, administrators and responsible authorities.",
        "Support with negotiation and documentation.",
        "Coordinating technical visits.",
      ]},
      { type: "bullets", heading: "Fixer services", items: [
        "Local research and information gathering.",
        "Vendor referrals and coordination.",
        "Liaison with communities, institutions and local agents.",
        "Support with permits, authorizations and documents.",
        "Hiring teams and resources, as defined by the model.",
        "Field production and schedule follow-up.",
        "Cultural translation and operational guidance.",
        "Logistics, security and travel plans.",
      ]},
      { type: "bullets", heading: "For which projects", items: [
        "Advertising and brand campaigns.",
        "Film, series, documentaries and television.",
        "Photography and digital content.",
        "Creators and international teams.",
        "Events, experiences and activations.",
        "Field research and institutional projects.",
      ]},
    ],
    ctaLabel: "Send us your brief",
    ctaHref: "/contato",
  },

  "receptivo-drivers-locacoes": {
    eyebrow: "GROUND TRANSPORT, DRIVERS & RENTALS",
    title: "Logistics start before arrival.",
    intro: "Teams, guests and resources need to be in the right place, at the right time, with enough information to follow the plan.",
    lead: "Creation coordinates arrival, stay and travel logistics for productions, events and special projects.",
    parentLabel: "Operations",
    parentHref: "/operacoes",
    blocks: [
      { type: "cards", heading: "What we can coordinate", items: [
        { title: "Arrivals and departures", description: "Reception at airports, bus stations, hotels, production bases and other defined points." },
        { title: "Transfers and drivers", description: "Drivers, executive vehicles, vans, buses, utility vehicles and other resources compatible with travel." },
        { title: "Routes and schedules", description: "Route planning, departure windows, meeting points, buffer time and operational updates." },
        { title: "Lodging and bases", description: "Research and coordination of hotels, houses, apartments, support rooms, green rooms and operational bases." },
        { title: "Resource rentals", description: "Vehicles, equipment, furniture, structures, communication, support and other items within scope." },
        { title: "On-the-ground support", description: "Service information, guest follow-up, production support and troubleshooting during the schedule." },
      ]},
      { type: "bullets", heading: "Who it's for", items: [
        "Film and photography crews.",
        "Guests, speakers and executives.",
        "Artists, creators and influencers.",
        "Brand, agency and production company teams.",
        "Delegations and institutional groups.",
        "Technical teams and vendors.",
      ]},
      { type: "bullets", heading: "Information we organize", items: [
        "Names, contacts and owners.",
        "Flights, times and arrival points.",
        "Lodging and addresses.",
        "Consolidated schedule.",
        "Vehicles, capacity and luggage.",
        "Credentials, access and authorizations.",
        "Emergency and escalation contacts.",
        "Backup plan for delays and changes.",
      ]},
    ],
    ctaLabel: "Plan your logistics",
    ctaHref: "/contato",
  },

  inovacao: {
    eyebrow: "INNOVATION",
    title: "Ideas gain value when they become projects.",
    intro: "Innovation doesn't start in a workshop and doesn't end in a presentation. It needs a relevant problem, decision criteria, mobilized people, and a path to test, learn and implement.",
    lead: "Creation structures and runs innovation initiatives connected to strategy and the organization's real capacity.",
    image: { src: "/images/blockchain-rio.webp", alt: "Blockchain Rio — innovation event run by Creation" },
    parentLabel: "Solutions",
    parentHref: "/solucoes",
    blocks: [
      { type: "cards", heading: "Fronts of work", items: [
        { title: "Innovation strategy", description: "Reading context, defining priority themes, objectives, portfolio, governance and indicators." },
        { title: "Challenge design", description: "Formulating the problem, guiding questions, criteria, audiences, data and participation conditions." },
        { title: "Programs and journeys", description: "Structuring hackathons, labs, sprints, open calls, ideation cycles, acceleration and open innovation." },
        { title: "Facilitation and content", description: "Workshops, meetups, mentoring, curation, materials and running collaborative processes." },
        { title: "Experimentation", description: "Hypotheses, prototypes, test plans, validation criteria and learning records." },
        { title: "Implementation", description: "Turning selected solutions into projects, with owners, resources, timeline and governance." },
      ]},
      { type: "bullets", heading: "Questions that organize a program", items: [
        "What problem needs to be solved, and why now?",
        "What's already known, and what still needs to be investigated?",
        "Who lives the problem, and who can decide on the solution?",
        "What constraints can't be ignored?",
        "How will proposals be compared?",
        "What resources will exist to test and implement?",
        "Who takes on continuity after the program?",
      ]},
      { type: "steps", heading: "How we work", items: [
        { number: "01", title: "Investigate", description: "Context, problem, audiences, constraints and evidence." },
        { number: "02", title: "Design", description: "Format, journey, governance, criteria, resources and communication." },
        { number: "03", title: "Mobilize", description: "Participants, specialists, partners, mentors and decision-makers." },
        { number: "04", title: "Run", description: "Content, facilitation, operation, records and follow-up." },
        { number: "05", title: "Unfold", description: "Selection, pilots, projects, learnings and next steps." },
      ]},
      { type: "bullets", heading: "Possible deliverables", items: [
        "Innovation diagnosis.",
        "Priority thesis or agenda.",
        "Opportunity map.",
        "Program architecture.",
        "Rules and selection criteria.",
        "Mobilization plan.",
        "Participant journey.",
        "Backlog of hypotheses and experiments.",
        "Pilot plan.",
        "Governance model.",
        "Results report and recommendations.",
      ]},
    ],
    ctaLabel: "Talk about your challenge",
    ctaHref: "/contato",
  },

  impacto: {
    eyebrow: "IMPACT",
    title: "Impact that is built and proven.",
    intro: "Social intention doesn't replace strategy, management or evidence. Creation helps companies, organizations and partners turn commitments into structured programs.",
    lead: "With defined audiences, clear responsibilities and follow-up compatible with the change being pursued.",
    image: { src: "/images/impacto-artesanato.webp", alt: "Local artisan market, part of a social impact program run by Creation" },
    parentLabel: "Solutions",
    parentHref: "/solucoes",
    blocks: [
      { type: "cards", heading: "Fronts of work", items: [
        { title: "Social and territorial diagnosis", description: "Reading context, audiences, assets, vulnerabilities, actors, existing initiatives, data and knowledge gaps." },
        { title: "Impact strategy", description: "Defining priorities, audiences, objectives, principles, criteria and alignment with the organization's strategy." },
        { title: "Theory of change", description: "Organizing the expected relationships between resources, activities, outputs, results and impacts, including assumptions and external factors." },
        { title: "Program design", description: "Scope, participant journey, partners, governance, budget, timeline, risks and indicators." },
        { title: "Management and operation", description: "Coordinating teams, partners, territories, vendors, decisions and deliverables." },
        { title: "Monitoring and evaluation", description: "Evaluative questions, indicators, sources, instruments, analysis, limitations and communication of results." },
      ]},
      { type: "bullets", heading: "What we distinguish", intro: "This distinction reduces the risk of presenting activity volume as proven transformation.", items: [
        "Input: resource used.",
        "Activity: action carried out.",
        "Output: product or service delivered.",
        "Reach: people or organizations involved.",
        "Result: change observed in the audience or system.",
        "Impact: change of greater scale or duration, analyzed with attention to contribution, attribution and context.",
      ]},
      { type: "bullets", heading: "Possible deliverables", items: [
        "Diagnosis or baseline.",
        "Stakeholder map.",
        "Strategy of action.",
        "Theory of change.",
        "Program design.",
        "Logical framework.",
        "Implementation plan.",
        "Governance model.",
        "Risk matrix.",
        "Monitoring and evaluation plan.",
        "Indicator catalog.",
        "Dashboard or report.",
        "Results evaluation.",
      ]},
    ],
    childrenLabel: "Related specialty",
    children: [
      { title: "Cause Marketing", description: "Strategy that connects brand, cause and action, with partnership, governance, experience and responsible communication.", href: "/impacto/marketing-de-causa" },
    ],
    ctaLabel: "Talk about your initiative",
    ctaHref: "/contato",
  },

  "marketing-de-causa": {
    eyebrow: "CAUSE MARKETING",
    title: "A cause can't be just a campaign.",
    intro: "When a brand associates itself with a social issue, it takes on responsibility for what it promises, how it acts, and who it involves.",
    lead: "Creation structures initiatives that connect positioning, partnership, experience and concrete delivery.",
    parentLabel: "Impact",
    parentHref: "/impacto",
    blocks: [
      { type: "cards", heading: "What we structure", items: [
        { title: "Brand-cause fit", description: "Analysis of history, values, track record, audiences, risks and possible contribution." },
        { title: "Initiative strategy", description: "Objective, audiences, proposal, thesis of action, expected results and decision criteria." },
        { title: "Mapping and partnership", description: "Identifying, evaluating and building relationships with organizations, specialists, territories and networks." },
        { title: "Concept and experience", description: "Translating the strategy into a program, campaign, content, event, activation or engagement journey." },
        { title: "Governance", description: "Roles, approvals, image use, resources, integrity, follow-up and risk response." },
        { title: "Execution and evidence", description: "Production, management, indicators, records, accountability and learnings." },
      ]},
      { type: "bullets", heading: "Possible formats", items: [
        "Campaigns tied to a concrete action.",
        "Customer or employee engagement programs.",
        "Purpose-driven activations and experiences.",
        "Events, meetups and mobilizations.",
        "Special products or editions.",
        "Sales-linked donations, with transparent rules.",
        "Content and education platforms.",
        "Territorial partnerships.",
      ]},
      { type: "bullets", heading: "Questions that need answering", items: [
        "Why should this brand act on this cause?",
        "What concrete need will be addressed?",
        "Who takes part in the decisions?",
        "Which organization has legitimacy and capacity on the topic?",
        "What will be delivered, to whom and over what period?",
        "What happens when the campaign ends?",
      ]},
      { type: "bullets", heading: "Possible deliverables", items: [
        "Fit and risk analysis.",
        "Cause and opportunity map.",
        "Strategy and core narrative.",
        "Stakeholder map.",
        "Partner selection criteria.",
        "Program or campaign design.",
        "Governance model.",
        "Mobilization and content plan.",
        "Indicator matrix.",
        "Transparency protocol.",
      ]},
    ],
    ctaLabel: "Talk about your initiative",
    ctaHref: "/contato",
  },

  "branding-experiencias": {
    eyebrow: "BRANDING & EXPERIENCES",
    title: "Strategy that can be seen, lived and remembered.",
    intro: "A brand becomes concrete in the encounters it produces. Creation connects positioning, concept and operation to create experiences consistent with what the organization wants to represent.",
    lead: "And capable of working in the real world.",
    image: { src: "/images/reservax-lounge.webp", alt: "ReservaX Lounge brand activation, produced by Creation" },
    parentLabel: "Solutions",
    parentHref: "/solucoes",
    blocks: [
      { type: "cards", heading: "Fronts of work", items: [
        { title: "Brand strategy", description: "Positioning, value proposition, audiences, messaging, territories of expression and coherence criteria." },
        { title: "Creative concept", description: "Central idea, narrative, language, experience and possible extensions." },
        { title: "Brand experience", description: "Journey, touchpoints, interactions, environments, content, services and team behavior." },
        { title: "Activations and live marketing", description: "Designing and running in-person, hybrid or traveling activations." },
        { title: "Events and gatherings", description: "Proprietary formats, launches, communities, experiences for internal and external audiences." },
        { title: "Content and partnerships", description: "Curation, creators, specialists, organizations, territories and networks compatible with the proposal." },
      ]},
      { type: "bullets", heading: "Experiences we can structure", items: [
        "Brand activations.",
        "Proprietary launches and gatherings.",
        "Cultural experiences.",
        "Relationship-building actions.",
        "Community programs.",
        "Fairs, exhibits and brand spaces.",
        "Employee experiences.",
        "Campaigns with territorial presence.",
      ]},
      { type: "bullets", heading: "What needs to stay coherent", items: [
        "Promise — what the brand states and what expectation it creates.",
        "Participation — what the audience can do, feel, learn or take with them.",
        "Operation — how space, staff, queue, access, content, service and technology sustain the experience.",
        "Continuity — what happens after the encounter, and how the relationship can continue.",
      ]},
      { type: "bullets", heading: "Possible deliverables", items: [
        "Brand and context diagnosis.",
        "Positioning or messaging platform.",
        "Experience concept and narrative.",
        "Journey architecture.",
        "Touchpoint plan.",
        "Creative and production brief.",
        "Content and partner curation.",
        "Activation plan.",
        "Budget and timeline.",
        "Indicators and report.",
      ]},
    ],
    ctaLabel: "Talk about your brand",
    ctaHref: "/contato",
  },

  "como-trabalhamos": {
    eyebrow: "HOW WE WORK",
    title: "Understand. Structure. Execute. Prove.",
    intro: "Different projects require different teams, tools and paths. What stays constant is a disciplined way of turning a need into direction, structure, delivery and evidence.",
    lead: "We don't call this a proprietary methodology. The value lies in choosing and applying the right method for each decision, not in inventing names for known stages.",
    blocks: [
      { type: "bullets", heading: "The journey doesn't have to start at the beginning", items: [
        "A still-diffuse challenge might start with Understand.",
        "An approved initiative might start with Structure.",
        "A planned project might need Execute.",
        "A completed delivery might need Prove.",
      ]},
      { type: "bullets", heading: "Clear responsibilities before execution", intro: "Every proposal should define:", items: [
        "What Creation takes on.",
        "What stays with the client.",
        "Which decisions depend on third parties.",
        "Which deliverables will be produced.",
        "How changes will be approved.",
        "When the work will be considered complete.",
      ]},
      { type: "bullets", heading: "Tools at the service of the project", intro: "SWOT, PESTEL, BPMN, Canvas, Design Thinking, Lean, Kanban, Scrum, RACI, OKRs and other tools can be used when they help answer a real question. We don't apply a tool because it's well known — we choose the resource based on the problem, the team's maturity, and the decision that needs to be made.", items: ["SWOT and PESTEL", "BPMN and Canvas", "Design Thinking and Lean", "Kanban and Scrum", "RACI and OKRs"] },
    ],
    childrenLabel: "The four stages",
    children: [
      { title: "01 — Understand", description: "We investigate the context, the audiences involved, needs, constraints and the expected result before proposing a solution.", href: "/contato" },
      { title: "02 — Structure", description: "We turn understanding into scope, priorities, governance, team, budget, timeline, risks and indicators.", href: "/contato" },
      { title: "03 — Execute", description: "We mobilize people, partners and resources, coordinate decisions and drive execution through to delivery.", href: "/contato" },
      { title: "04 — Prove", description: "We monitor, document and analyze results to demonstrate deliverables, assess the value generated and guide next steps.", href: "/contato" },
    ],
    ctaLabel: "Tell us about your project",
    ctaHref: "/contato",
  },
};

export const homeCapacidades: HomeCapacidade[] = [
  {
    title: "Strategy",
    tagline: "Clarity to decide.",
    description: "We investigate the context, organize information and turn complexity into direction. Strategy defines the problem, guides choices and builds a viable path for the project.",
    items: ["Market Intelligence", "Diagnosis and Planning", "Project Structuring and Viability"],
    href: "/solucoes/estrategia",
    linkLabel: "See Strategy",
  },
  {
    title: "Management",
    tagline: "Rhythm to move forward.",
    description: "We turn direction into scope, responsibilities and decisions. We structure governance, teams, processes and indicators so the project moves forward with rhythm, control and transparency.",
    items: ["Project Management and PMO", "Business Process Management", "Governance, KPIs and Risk"],
    href: "/solucoes/gestao",
    linkLabel: "See Management",
  },
  {
    title: "Operations",
    tagline: "Execution to deliver.",
    description: "We mobilize people, partners, vendors, logistics, spaces and resources to turn planning into delivery, coordinating the operation from preparation through completion.",
    items: ["Event Management and Production", "Executive Production and Logistics", "Location & Fixer", "Ground Transport, Drivers and Rentals"],
    href: "/operacoes",
    linkLabel: "See Operations",
  },
];

export const homeEspecialidades: HomeEspecialidade[] = [
  {
    title: "Innovation",
    tagline: "Ideas gain value when they become projects.",
    description: "We structure and run innovation programs, challenges, hackathons, ideathons and journeys.",
    href: "/inovacao",
    linkLabel: "See Innovation",
    image: { src: "/images/hacking-rio.webp", alt: "Hacking.Rio — innovation program run by Creation" },
  },
  {
    title: "Impact",
    tagline: "Impact that is built and proven.",
    description: "We design, manage and run social responsibility programs, cause marketing and territorial development.",
    href: "/impacto",
    linkLabel: "See Impact",
    image: { src: "/images/impacto-hero.webp", alt: "Social impact program on the ground, run by Creation" },
  },
  {
    title: "Branding & Experiences",
    tagline: "Strategy that can be seen, lived and remembered.",
    description: "We turn positioning into identity, narrative, content, activations and experiences.",
    href: "/branding-experiencias",
    linkLabel: "See Branding & Experiences",
    image: { src: "/images/reservax-lounge.webp", alt: "ReservaX Lounge brand activation, produced by Creation" },
  },
];

export const homeSolucoes: HomeSolucao[] = [
  {
    title: "Creation Ops Rio",
    description: "Integrated local operation for agencies, production companies, brands and teams running projects in Rio de Janeiro. Location, fixer, ground transport, drivers, rentals, vendors and logistics under a single coordination.",
    href: "/creator-ops-rio",
  },
];

export const casesStub: CaseStub[] = [
  {
    title: "Hacking.Rio",
    client: "Íons Innovation",
    context: "Executive production and operation of four editions across three different formats (in-person, digital and metaverse), integrating participants, mentors, partners and vendors.",
    numbers: ["4 editions", "3 formats", "5,000+ competitors", "170,000+ people reached"],
  },
  {
    title: "Hacking.Help",
    client: "Íons Innovation",
    context: "Concept and executive production of an online marathon created quickly to keep social-purpose mobilization going during the pandemic.",
    numbers: ["1,533 competitors", "5 Portuguese-speaking countries", "R$500K in estimated earned media"],
  },
  {
    title: "HR Talks",
    client: "Íons Innovation",
    context: "Executive production of a long-form international digital program, coordinating agenda, speakers and live broadcast.",
    numbers: ["15,500 registrants", "172 global speakers", "40 hours of live content"],
  },
  {
    title: "Pertinho de Casa — School and Fairs",
    client: "Rede Asta and Porto Sudeste",
    context: "Territorial coordination of a business school and sales fairs to strengthen local entrepreneurs.",
    numbers: ["2 fronts of work", "6 sales events", "R$19,649 in tracked sales"],
  },
  {
    title: "Pertinho de Casa — Platform",
    client: "Rede Asta and Porto Sudeste",
    context: "Recruiting sellers, coordinating the Local Economy Committee, and quarterly follow-up on the platform.",
    numbers: ["241 entrepreneurs", "56 neighborhoods across Itaguaí and Seropédica", "R$30,650.11 in registered revenue"],
  },
  {
    title: "World Creativity Day",
    client: "Centro Cultural Banco do Brasil Rio de Janeiro",
    context: "Concept and execution of in-person and online programming on creativity, spread across different venues and days.",
    numbers: ["3 days of programming", "2 venues", "1,000+ people reached", "50+ online speakers"],
  },
];
