import type { StubPageData, HomeCapacidade, HomeEspecialidade, HomeSolucao, CaseStub } from "./types";

export const stubData: Record<string, StubPageData> = {
  solucoes: {
    eyebrow: "SOLUCIONES",
    title: "Soluciones que empiezan por el desafío, no por el catálogo.",
    intro:
      "Creation combina estrategia, gestión y capacidad operativa según el contexto, el momento y la estructura de cada proyecto.",
    lead: "Podemos asumir un frente específico o conectar todo el recorrido, desde el entendimiento inicial hasta la entrega y el análisis de resultados.",
    blocks: [
      {
        type: "cards",
        heading: "Empiece por lo que necesita suceder",
        intro: "No necesita conocer el vocabulario de una consultoría para encontrar la solución correcta. El punto de partida es reconocer qué está impidiendo que el proyecto avance.",
        items: [
          { title: "Necesito entender y decidir", description: "Cuando hay una oportunidad, una intención o mucha información, pero todavía falta claridad para elegir el camino. Podemos contribuir con: inteligencia de mercado, investigación, diagnóstico, planificación y definición de prioridades." },
          { title: "Necesito estructurar y viabilizar", description: "Cuando la idea ya existe, pero todavía necesita alcance, gobernanza, presupuesto, cronograma, socios, riesgos e indicadores para volverse ejecutable. Podemos contribuir con: estructuración de proyectos, modelado, planificación de recursos y estrategia de viabilización." },
          { title: "Necesito organizar y gestionar", description: "Cuando el proyecto está en marcha, pero decisiones, responsabilidades, procesos o información permanecen dispersos. Podemos contribuir con: gestión de proyectos y PMO, gestión de procesos, gobernanza, indicadores y coordinación de equipos." },
          { title: "Necesito ejecutar y operar", description: "Cuando la entrega depende de proveedores, producción, logística, autorizaciones, personas y decisiones coordinadas en el mundo real. Podemos contribuir con: gestión de eventos, producción ejecutiva, location services, fixer, receptivo, choferes y locaciones." },
          { title: "Necesito movilizar personas y públicos", description: "Cuando el proyecto necesita conectar una organización con participantes, comunidades, socios, causas o consumidores. Podemos contribuir con: innovación, programas de impacto, marketing de causa, branding, activaciones y experiencias." },
          { title: "Necesito medir y demostrar", description: "Cuando es necesario organizar datos, seguir indicadores, documentar entregas y producir una lectura responsable de los resultados. Podemos contribuir con: diseño de indicadores, gobernanza de datos, evaluación, informes y medición de impacto o eventos." },
        ],
      },
      {
        type: "bullets",
        heading: "Diferentes formas de trabajar con nosotros",
        items: [
          "Proyecto integrado — Creation conecta estrategia, gestión y operación y responde por todo el recorrido definido en el contrato.",
          "Frente específico — asumimos una etapa o competencia delimitada, integrada a la estructura ya existente del cliente.",
          "Extensión del equipo — sumamos capacidad temporal de gestión, producción o coordinación a equipos internos, agencias y productoras.",
          "En cualquier formato, alcance, responsabilidades, entregas y criterios de conclusión se definen antes del inicio.",
        ],
      },
    ],
    childrenLabel: "Capacidades y especialidades",
    children: [
      { title: "Estrategia", description: "Claridad para decidir: inteligencia de mercado, diagnóstico y planificación, estructuración y viabilización de proyectos.", href: "/solucoes/estrategia" },
      { title: "Gestión", description: "Ritmo para avanzar: gestión de proyectos y PMO, procesos de negocio, gobernanza e indicadores.", href: "/solucoes/gestao" },
      { title: "Operaciones", description: "Ejecución para realizar: gestión de eventos, producción ejecutiva, location & fixer, receptivo y logística.", href: "/operacoes" },
      { title: "Innovación", description: "Proyectos, programas, hackathons, ideathons y jornadas para transformar desafíos en soluciones aplicables.", href: "/inovacao" },
      { title: "Impacto", description: "Programas de responsabilidad social, iniciativas territoriales, estructuración de organizaciones y medición de resultados.", href: "/impacto" },
      { title: "Branding & Experiencias", description: "Estrategia de marca, narrativa, contenido, activaciones y experiencias que conectan posicionamiento y presencia.", href: "/branding-experiencias" },
      { title: "Creation Ops Rio", description: "Operación local integrada en Río de Janeiro para agencias, productoras, marcas y equipos internacionales.", href: "/creator-ops-rio" },
    ],
    ctaBody: "Cuéntenos el contexto, el momento del proyecto y lo que necesita suceder. La primera conversación sirve para identificar el problema, no para forzar una solución ya lista.",
    ctaLabel: "Cuéntenos su proyecto",
    ctaHref: "/contato",
  },

  estrategia: {
    eyebrow: "ESTRATEGIA",
    title: "Claridad antes de la acción.",
    intro: "Investigamos el contexto, organizamos la información y estructuramos las decisiones que permiten al proyecto avanzar con dirección.",
    lead: "Para Creation, la estrategia no es un documento aislado de la ejecución. Es la definición de lo que necesita suceder, por qué ese camino tiene sentido y qué condiciones harán posible su realización.",
    parentLabel: "Soluciones",
    parentHref: "/solucoes",
    blocks: [
      { type: "bullets", heading: "Cuándo la Estrategia es el punto de entrada", items: [
        "Existe una oportunidad, pero todavía no una decisión estructurada.",
        "Hay mucha información y opiniones, pero falta una lectura común.",
        "La organización necesita comprender su mercado, público o competencia.",
        "Una idea necesita transformarse en un proyecto viable.",
        "La inversión es relevante y las premisas todavía son frágiles.",
        "Diferentes áreas necesitan acordar objetivo, prioridad y camino.",
        "Un proyecto se estancó y es necesario revisar el problema antes de acelerar de nuevo.",
      ]},
      { type: "bullets", heading: "Entregables posibles", intro: "Según el alcance, el frente de Estrategia puede producir:", items: [
        "Informe de investigación e inteligencia.",
        "Diagnóstico organizacional, de mercado o de proyecto.",
        "Escenarios y criterios de decisión.",
        "Definición de públicos y stakeholders.",
        "Propuesta de valor o tesis de actuación.",
        "Objetivos, prioridades y hoja de ruta.",
        "Modelo inicial del proyecto.",
        "Plan de acción.",
        "Mapa de riesgos y premisas.",
        "Presentación ejecutiva para la decisión.",
      ]},
      { type: "bullets", heading: "Dónde se aplica esta capacidad", intro: "La Estrategia puede movilizarse en proyectos de:", items: [
        "Innovación.",
        "Responsabilidad social e impacto.",
        "Branding y experiencias.",
        "Eventos y activaciones.",
        "Expansión de PyMEs.",
        "Economía creativa.",
        "Procesos y transformación organizacional.",
        "Proyectos territoriales.",
      ]},
    ],
    childrenLabel: "Lo que podemos asumir",
    children: [
      { title: "Inteligencia de Mercado", description: "Investigación y análisis para comprender mercado, competencia, públicos, tendencias, riesgos y oportunidades antes de decidir.", href: "/solucoes/inteligencia-de-mercado" },
      { title: "Diagnóstico y Planificación", description: "Lectura estructurada de la situación actual, definición del problema, prioridades, objetivos y plan de acción.", href: "/solucoes/diagnostico-e-planejamento" },
      { title: "Estructuración y Viabilización de Proyectos", description: "Transformación de una intención en alcance, gobernanza, presupuesto, cronograma, indicadores y estrategia de recursos.", href: "/solucoes/estruturacao-de-projetos" },
    ],
    ctaLabel: "Conversemos sobre el desafío",
    ctaHref: "/contato",
  },

  "inteligencia-de-mercado": {
    eyebrow: "INTELIGENCIA DE MERCADO",
    title: "Decidir mejor empieza por entender el mercado real.",
    intro: "Las opiniones internas, las tendencias y los datos aislados no forman una estrategia. La inteligencia de mercado conecta evidencias para responder preguntas específicas sobre demanda, competencia, públicos, contexto y oportunidad.",
    lead: "El trabajo empieza por la decisión que hay que tomar. La investigación está diseñada para reducir la incertidumbre útil, no para acumular información.",
    parentLabel: "Estrategia",
    parentHref: "/solucoes/estrategia",
    blocks: [
      { type: "bullets", heading: "Cuándo contratar Inteligencia de Mercado", items: [
        "Antes de lanzar un producto, servicio, programa o evento.",
        "Al entrar en un nuevo territorio, público o segmento.",
        "Cuando la competencia cambió y la posición de la organización perdió claridad.",
        "Para evaluar una oportunidad antes de invertir recursos relevantes.",
        "Cuando las decisiones internas se basan en percepciones conflictivas.",
        "Para comprender el comportamiento, las necesidades y las barreras de un público.",
        "Antes de redefinir posicionamiento, portafolio o propuesta de valor.",
      ]},
      { type: "bullets", heading: "Preguntas que podemos ayudar a responder", items: [
        "¿Cuál es el tamaño y la configuración posible de la oportunidad?",
        "¿Quién ya ofrece respuestas similares y cómo se posiciona?",
        "¿Qué valoran, rechazan o todavía no encuentran los públicos?",
        "¿Qué tendencias realmente afectan al proyecto y cuáles son solo ruido?",
        "¿Qué barreras de adopción, operación o regulación deben considerarse?",
        "¿Qué segmentos merecen prioridad?",
        "¿Qué necesita probarse antes de una decisión mayor?",
      ]},
      { type: "cards", heading: "Alcance posible", items: [
        { title: "Investigación documental y datos secundarios", description: "Relevamiento de estudios, bases públicas, documentos, informes sectoriales e información disponible." },
        { title: "Benchmarking y competencia", description: "Mapeo de referencias, ofertas, modelos de negocio, mensajes, experiencias y movimientos competitivos." },
        { title: "Públicos y demanda", description: "Entrevistas, encuestas, escucha cualitativa, análisis de recorrido e investigación de necesidades." },
        { title: "Tendencias y escenarios", description: "Identificación de fuerzas de cambio, señales emergentes, riesgos y posibles consecuencias para la decisión." },
        { title: "Contexto territorial", description: "Lectura de actores, infraestructura, dinámicas locales, oportunidades y restricciones del territorio." },
        { title: "Síntesis estratégica", description: "Organización de las evidencias en implicaciones, opciones y recomendaciones prácticas." },
      ]},
      { type: "bullets", heading: "Lo que usted recibe", intro: "El formato depende de la pregunta, pero puede incluir:", items: [
        "Plan de investigación.",
        "Mapa de mercado o ecosistema.",
        "Análisis de competidores y referencias.",
        "Perfiles o segmentos de público.",
        "Síntesis de entrevistas e investigación de campo.",
        "Tendencias con implicaciones para el negocio.",
        "Escenarios y criterios de decisión.",
        "Oportunidades priorizadas.",
        "Recomendaciones y próximas pruebas.",
        "Informe y presentación ejecutiva.",
      ]},
      { type: "steps", heading: "Cómo lo conducimos", items: [
        { number: "01", title: "Definición de la decisión", description: "Alineamos qué necesita decidirse, por quién y en qué plazo." },
        { number: "02", title: "Diseño de la investigación", description: "Elegimos fuentes, métodos, muestra, profundidad y criterios compatibles con la decisión y el presupuesto." },
        { number: "03", title: "Recolección y análisis", description: "Reunimos datos, identificamos patrones y registramos limitaciones." },
        { number: "04", title: "Interpretación", description: "Traducimos evidencias en implicaciones, hipótesis y opciones." },
        { number: "05", title: "Recomendación", description: "Presentamos lo que los datos permiten concluir, lo que sigue siendo incierto y qué pasos reducen el riesgo siguiente." },
      ]},
      { type: "bullets", heading: "Para quién", items: [
        "PyMEs evaluando expansión o una nueva oferta.",
        "Áreas de innovación, estrategia y marketing.",
        "Institutos y áreas de responsabilidad social.",
        "Creators y negocios de la economía creativa.",
        "Agencias y productoras que preparan proyectos para clientes.",
        "Organizaciones que necesitan entender un territorio antes de actuar.",
      ]},
      { type: "bullets", heading: "Lo que una investigación responsable no promete", items: [
        "La inteligencia de mercado reduce la incertidumbre, pero no elimina el riesgo ni predice el futuro con exactitud. Toda conclusión depende de la calidad de las fuentes, el recorte, el acceso a los públicos y el momento analizado. Las premisas, limitaciones y vacíos se presentan junto con las recomendaciones.",
      ]},
    ],
    ctaLabel: "Plantee su pregunta de negocio",
    ctaHref: "/contato",
  },

  "diagnostico-e-planejamento": {
    eyebrow: "DIAGNÓSTICO Y PLANIFICACIÓN",
    title: "Antes del plan, el problema correcto.",
    intro: "Planificar demasiado pronto puede organizar la respuesta equivocada. El diagnóstico esclarece qué está pasando, por qué importa y qué condiciones necesitan cambiar.",
    lead: "La planificación transforma esa lectura en prioridades, acciones, responsables y criterios de seguimiento.",
    parentLabel: "Estrategia",
    parentHref: "/solucoes/estrategia",
    blocks: [
      { type: "bullets", heading: "Señales de que el diagnóstico es necesario", items: [
        "El pedido inicial describe una solución, pero el problema todavía no está claro.",
        "Cada área presenta una lectura diferente de la situación.",
        "Hay demasiadas iniciativas y pocas prioridades.",
        "El proyecto perdió ritmo y nadie logra señalar una única causa.",
        "Las metas se definieron sin conexión con capacidad, recursos o público.",
        "Un cambio importante necesita implementarse, pero todavía no existe un plan compartido.",
      ]},
      { type: "bullets", heading: "Lo que investigamos", items: [
        "contexto organizacional e histórico;",
        "objetivos, resultados e indicadores existentes;",
        "estructura, roles y gobernanza;",
        "procesos y flujos de decisión;",
        "públicos, clientes, usuarios o comunidades;",
        "equipo, competencias y capacidad disponible;",
        "recursos, restricciones y dependencias;",
        "riesgos, conflictos e iniciativas anteriores.",
      ]},
      { type: "steps", heading: "Del diagnóstico al plan", items: [
        { number: "01", title: "Encuadre", description: "Definimos la pregunta central, los públicos involucrados y el uso esperado del trabajo." },
        { number: "02", title: "Escucha y recolección", description: "Analizamos documentos, datos y experiencias de las personas relevantes." },
        { number: "03", title: "Síntesis", description: "Identificamos causas, patrones, tensiones, brechas y oportunidades." },
        { number: "04", title: "Priorización", description: "Comparamos temas por impacto, urgencia, viabilidad y dependencias." },
        { number: "05", title: "Planificación", description: "Transformamos prioridades en objetivos, iniciativas, responsables, plazos, recursos e indicadores." },
      ]},
      { type: "bullets", heading: "Entregables posibles", items: [
        "Diagnóstico ejecutivo.",
        "Mapa de causas y efectos.",
        "Análisis de stakeholders.",
        "Matriz de prioridades.",
        "Definición de objetivos y resultados esperados.",
        "Hoja de ruta de implementación.",
        "Plan de acción con responsables y plazos.",
        "Mapa de riesgos y dependencias.",
        "Sistema inicial de indicadores.",
      ]},
      { type: "bullets", heading: "Aplicaciones frecuentes", items: [
        "Planificación de nuevos proyectos.",
        "Revisión de iniciativas estancadas.",
        "Preparación de programas de impacto.",
        "Organización de áreas o frentes de trabajo.",
        "Planificación de eventos y experiencias complejas.",
        "Diseño de programas de innovación.",
        "Preparación para la expansión o el cambio de posicionamiento.",
        "Definición de prioridades en PyMEs.",
      ]},
      { type: "bullets", heading: "Planificación que reconoce límites", items: [
        "Un plan responsable no presupone equipo, presupuesto o datos que no existen. Explicita dependencias, elecciones y renuncias. Cuando el diagnóstico indica que la organización todavía no tiene condiciones para ejecutar determinada iniciativa, la planificación debe incluir cómo construir esa capacidad, y no solo establecer una fecha optimista.",
      ]},
    ],
    ctaLabel: "Conversemos sobre el contexto",
    ctaHref: "/contato",
  },

  "estruturacao-de-projetos": {
    eyebrow: "ESTRUCTURACIÓN Y VIABILIZACIÓN DE PROYECTOS",
    title: "Una idea solo se vuelve proyecto cuando puede ejecutarse.",
    intro: "Estructuramos iniciativas para que puedan ser comprendidas, decididas, financiadas, gestionadas y realizadas.",
    lead: "Eso significa transformar la intención en objetivos, alcance, entregas, gobernanza, recursos, cronograma, riesgos e indicadores coherentes entre sí.",
    parentLabel: "Estrategia",
    parentHref: "/solucoes/estrategia",
    blocks: [
      { type: "bullets", heading: "Cuándo una iniciativa todavía no es un proyecto", items: [
        "Objetivos amplios sin entregas definidas.",
        "Público o beneficiarios descritos de forma genérica.",
        "Presupuesto sin memoria de cálculo.",
        "Cronograma sin dependencias ni responsables.",
        "Socios mencionados, pero todavía no movilizados.",
        "Indicadores que no pueden medirse.",
        "Expectativa de captación sin estrategia de financiamiento.",
      ]},
      { type: "cards", heading: "Lo que estructuramos", items: [
        { title: "Lógica del proyecto", description: "Problema, justificación, objetivos, públicos, resultados esperados y relación entre actividades y entregas." },
        { title: "Alcance y entregas", description: "Qué se hará, qué queda fuera, cómo se aceptará cada entrega y qué dependencias existen." },
        { title: "Gobernanza", description: "Roles, responsabilidades, foros de decisión, socios y formas de seguimiento." },
        { title: "Plan de realización", description: "Etapas, cronograma, equipo, proveedores, recursos, riesgos y operación necesaria." },
        { title: "Presupuesto", description: "Categorías de costo, premisas, cotizaciones, reservas y relación entre recursos y actividades." },
        { title: "Indicadores", description: "Cómo hacer seguimiento a ejecución, alcance, calidad, resultado y aprendizaje." },
        { title: "Viabilización", description: "Posibles modelos de contratación, patrocinio, alianza, convocatoria o incentivo, cuando sean compatibles con el proyecto." },
      ]},
      { type: "bullets", heading: "Entregables posibles", items: [
        "Documento estructurado del proyecto.",
        "Matriz lógica o teoría de cambio.",
        "Alcance y estructura analítica del proyecto.",
        "Plan de trabajo.",
        "Cronograma e hitos.",
        "Presupuesto y memoria de cálculo.",
        "Mapa de gobernanza y stakeholders.",
        "Matriz de riesgos.",
        "Plan de indicadores.",
        "Estrategia de alianzas y recursos.",
        "Presentación institucional o comercial.",
        "Adaptación para convocatoria, patrocinador o proceso decisorio específico.",
      ]},
      { type: "steps", heading: "Cómo trabajamos", items: [
        { number: "01", title: "Entendimiento", description: "Reunimos lo que ya existe y definimos las preguntas todavía sin respuesta." },
        { number: "02", title: "Arquitectura", description: "Conectamos problema, objetivos, públicos, actividades, entregas y resultados." },
        { number: "03", title: "Modelado", description: "Estructuramos gobernanza, cronograma, recursos, presupuesto, riesgos e indicadores." },
        { number: "04", title: "Validación", description: "Probamos coherencia, capacidad de ejecución y adecuación al proceso decisorio o mecanismo de financiamiento." },
        { number: "05", title: "Preparación", description: "Consolidamos documentos, presentaciones y próximos pasos para contratación, alianza o implementación." },
      ]},
      { type: "bullets", heading: "Proyectos que podemos estructurar", items: [
        "Iniciativas corporativas.",
        "Programas de innovación.",
        "Proyectos culturales y de economía creativa.",
        "Programas de responsabilidad social.",
        "Eventos y experiencias.",
        "Proyectos territoriales.",
        "Iniciativas propias.",
        "Proyectos para contratación directa, patrocinio, convocatorias o leyes de incentivo.",
        "La naturaleza del proyecto define qué especialistas, documentos y validaciones adicionales serán necesarios.",
      ]},
      { type: "bullets", heading: "Viabilizar no es prometer aprobación o captación", items: [
        "Creation puede estructurar el proyecto, identificar caminos, preparar materiales y apoyar la interlocución. La decisión de contratar, patrocinar, aprobar o financiar pertenece a terceros y depende de criterios que no controlamos. Nuestra responsabilidad es aumentar la consistencia, la claridad y la capacidad de ejecución de la propuesta, sin transformar la posibilidad en garantía.",
      ]},
    ],
    ctaLabel: "Estructure su proyecto",
    ctaHref: "/contato",
  },

  gestao: {
    eyebrow: "GESTIÓN",
    title: "La responsabilidad que no se transfiere.",
    intro: "Un plan no crea ritmo por sí solo. Los proyectos avanzan cuando las decisiones tienen responsables, la información circula, los riesgos se gestionan y los equipos saben qué debe suceder a continuación.",
    lead: "Creation estructura y conduce ese sistema de gestión, conectando estrategia, personas, procesos y entregas.",
    parentLabel: "Soluciones",
    parentHref: "/solucoes",
    blocks: [
      { type: "bullets", heading: "Cuándo la Gestión necesita entrar", items: [
        "El proyecto atraviesa varias áreas y no tiene un liderazgo de integración.",
        "Hay muchas reuniones, pero pocas decisiones registradas.",
        "Los plazos cambian sin que se comprendan los impactos.",
        "Equipos y proveedores trabajan con versiones diferentes del plan.",
        "El cliente tiene conocimiento técnico, pero no capacidad disponible para coordinarlo todo.",
        "Problemas recurrentes indican fallas de proceso, no solo de esfuerzo.",
        "La organización necesita seguir un portafolio, y no solo un proyecto.",
      ]},
      { type: "bullets", heading: "Gestión es más que seguimiento", intro: "Seguir significa observar lo que sucedió. Gestionar significa crear las condiciones para que las próximas decisiones sucedan en el momento correcto. Nuestro rol puede incluir:", items: [
        "transformar estrategia en plan de trabajo;",
        "definir gobernanza, roles y cadencia;",
        "coordinar equipos, socios y proveedores;",
        "mantener actualizados cronograma, presupuesto, riesgos y decisiones;",
        "resolver impedimentos y dependencias;",
        "preparar información para foros ejecutivos;",
        "registrar cambios de alcance;",
        "seguir indicadores y entregas;",
        "organizar el cierre y las lecciones aprendidas.",
      ]},
      { type: "cards", heading: "Formas de actuación", items: [
        { title: "Gestión integral del proyecto", description: "Asumimos la coordinación desde la estructuración hasta el cierre, dentro de las responsabilidades contratadas." },
        { title: "PMO del proyecto o portafolio", description: "Creamos y operamos la estructura de gobernanza, estándares, información y seguimiento para una o varias iniciativas." },
        { title: "Extensión del equipo", description: "Sumamos capacidad temporal de gestión a un área interna, agencia, productora u organización socia." },
        { title: "Implementación de procesos y gobernanza", description: "Estructuramos el sistema y acompañamos su adopción hasta que el equipo pueda operarlo." },
      ]},
      { type: "bullets", heading: "Lo que permanece con el cliente", items: [
        "La gestión no sustituye decisiones que pertenecen a la organización. La propuesta debe definir quién aprueba alcance, presupuesto, contratos, prioridades y cambios relevantes.",
        "Creation organiza información, recomienda caminos, conduce los foros y ejecuta las responsabilidades delegadas. El cliente mantiene los poderes de decisión que no hayan sido formalmente transferidos.",
      ]},
      { type: "bullets", heading: "Entregables posibles", items: [
        "Plan de proyecto.",
        "Estructura de gobernanza.",
        "Matriz de responsabilidades.",
        "Cronograma integrado.",
        "Presupuesto y control de costos.",
        "Mapa de riesgos, problemas y dependencias.",
        "Plan de comunicación y stakeholders.",
        "Actas y registro de decisiones.",
        "Dashboards e informes ejecutivos.",
        "Procesos y procedimientos.",
        "Informe de cierre y lecciones aprendidas.",
      ]},
    ],
    childrenLabel: "Lo que podemos asumir",
    children: [
      { title: "Gestión de Proyectos y PMO", description: "Planificación, gobernanza, coordinación, seguimiento y cierre de proyectos o portafolios.", href: "/solucoes/gestao-de-projetos" },
      { title: "Gestión de Procesos de Negocio", description: "Mapeo, rediseño e implementación de procesos para reducir la dependencia de las personas, el retrabajo y la pérdida de información.", href: "/solucoes/gestao-de-processos" },
      { title: "Gobernanza e Indicadores", description: "Roles, foros, criterios de decisión, indicadores y rutinas para transformar el seguimiento en acción.", href: "/solucoes/governanca-e-indicadores" },
    ],
    ctaLabel: "Conversemos sobre la gestión del proyecto",
    ctaHref: "/contato",
  },

  "gestao-de-projetos": {
    eyebrow: "GESTIÓN DE PROYECTOS Y PMO",
    title: "Los proyectos avanzan cuando las decisiones tienen dueño.",
    intro: "Coordinamos el sistema que conecta objetivo, alcance, equipos, presupuesto, plazo, riesgos y entregas.",
    lead: "La gestión transforma información dispersa en decisiones visibles y mantiene el trabajo en movimiento hasta la conclusión.",
    parentLabel: "Gestión",
    parentHref: "/solucoes/gestao",
    blocks: [
      { type: "bullets", heading: "El problema no siempre es la planificación inicial", intro: "Muchos proyectos comienzan con un cronograma y una lista de tareas. El problema surge cuando la realidad cambia y nadie puede responder rápidamente:", items: [
        "qué versión del plan es la vigente;",
        "quién decide cada tema;",
        "qué está retrasado y cuál es su efecto;",
        "qué riesgos necesitan acción;",
        "qué proveedor o área depende de quién;",
        "cuánto ya se ha comprometido;",
        "qué necesita llevarse al liderazgo.",
        "La gestión de proyectos crea esa visión común y la transforma en rutina de decisión.",
      ]},
      { type: "cards", heading: "Alcance posible", items: [
        { title: "Iniciación", description: "Objetivo, alcance, entregas, stakeholders, premisas, restricciones y criterios de éxito." },
        { title: "Planificación", description: "Cronograma, presupuesto, equipo, adquisiciones, comunicación, riesgos, calidad e indicadores." },
        { title: "Gobernanza", description: "Roles, foros, niveles de decisión, cadencia, registros y caminos de escalamiento." },
        { title: "Coordinación", description: "Seguimiento de equipos, socios, proveedores, dependencias y decisiones." },
        { title: "Control", description: "Monitoreo de plazo, costo, alcance, riesgos, problemas, cambios y entregas." },
        { title: "Cierre", description: "Aceptación, documentación, rendición de cuentas, lecciones aprendidas y transición." },
      ]},
      { type: "cards", heading: "PMO del tamaño que exige el contexto", intro: "Un PMO no tiene que significar una estructura pesada o permanente.", items: [
        { title: "PMO de proyecto", description: "Organiza gobernanza, información y seguimiento de una iniciativa específica." },
        { title: "PMO de programa", description: "Coordina proyectos relacionados, beneficios compartidos y dependencias entre frentes." },
        { title: "PMO de portafolio", description: "Apoya priorización, capacidad, indicadores y decisiones sobre varias iniciativas." },
        { title: "PMO temporal", description: "Implementa prácticas y opera la gestión durante una fase crítica, preparando la transferencia al equipo interno." },
      ]},
      { type: "bullets", heading: "Lo que puede entregarse", items: [
        "Acta de constitución o documento de iniciación.",
        "Plan integrado del proyecto.",
        "Estructura analítica y cronograma.",
        "Matriz de responsabilidades.",
        "Presupuesto y control de compromisos.",
        "Mapa de stakeholders.",
        "Matriz de riesgos y problemas.",
        "Flujo de cambios.",
        "Dashboard ejecutivo.",
        "Actas y registro de decisiones.",
        "Informes de estado.",
        "Plan de cierre y transición.",
      ]},
      { type: "bullets", heading: "Creation puede entrar en tres momentos", items: [
        "Antes del inicio — para estructurar el proyecto y preparar gobernanza, plan y movilización.",
        "Durante la ejecución — para asumir la coordinación, recuperar visibilidad y resolver bloqueos.",
        "En una fase crítica — para reorganizar un frente, preparar un evento, realizar una implementación o conducir el cierre.",
      ]},
      { type: "bullets", heading: "Trabajo integrado, responsabilidades explícitas", intro: "La propuesta define:", items: [
        "quién patrocina y decide;",
        "quién lidera técnicamente;",
        "qué coordina Creation;",
        "qué ejecutan los equipos internos;",
        "qué proveedores responden por entregas específicas;",
        "cómo se aprobarán los cambios y excepciones.",
        "No asumimos, por lenguaje comercial, responsabilidades que el contrato y la gobernanza no hayan transferido.",
      ]},
      { type: "bullets", heading: "Para quién", items: [
        "PyMEs sin estructura interna dedicada a proyectos.",
        "Áreas corporativas que conducen iniciativas transversales.",
        "Institutos y organizaciones sociales.",
        "Agencias y productoras que necesitan coordinación adicional.",
        "Programas de innovación, impacto, eventos y economía creativa.",
      ]},
    ],
    ctaLabel: "Hábleme de su proyecto",
    ctaHref: "/contato",
  },

  "gestao-de-processos": {
    eyebrow: "GESTIÓN DE PROCESOS DE NEGOCIO",
    title: "El trabajo necesita funcionar más allá de las personas que lo sostienen.",
    intro: "Cuando un proceso existe solo en la memoria de quien lo ejecuta, la organización queda vulnerable a atrasos, retrabajo, pérdida de información y decisiones inconsistentes.",
    lead: "Mapeamos cómo sucede el trabajo, rediseñamos lo que necesita cambiar y acompañamos la implementación hasta que el nuevo flujo pueda ser operado por el equipo.",
    parentLabel: "Gestión",
    parentHref: "/solucoes/gestao",
    blocks: [
      { type: "bullets", heading: "Señales de que el proceso necesita revisión", items: [
        "La misma tarea se ejecuta de maneras diferentes.",
        "La información necesita escribirse o verificarse varias veces.",
        "Las aprobaciones no tienen plazo, criterio o responsable claro.",
        "El cliente o usuario no sabe en qué etapa está.",
        "La operación depende excesivamente de una persona.",
        "Se implementaron herramientas sin rediseñar el flujo de trabajo.",
      ]},
      { type: "steps", heading: "Cómo lo conducimos", items: [
        { number: "01", title: "Priorizar", description: "Elegimos los procesos con mayor efecto sobre resultado, riesgo o experiencia." },
        { number: "02", title: "Comprender", description: "Mapeamos el flujo real, incluyendo los atajos y excepciones que rara vez aparecen en los manuales." },
        { number: "03", title: "Rediseñar", description: "Construimos el proceso futuro con participación de quien decide y de quien ejecuta." },
        { number: "04", title: "Implementar", description: "Definimos responsables, procedimientos, herramientas, capacitación y transición." },
        { number: "05", title: "Acompañar", description: "Medimos la adopción, corregimos fallas y preparamos la operación autónoma." },
      ]},
      { type: "bullets", heading: "Entregables posibles", items: [
        "Inventario de procesos.",
        "Mapas del estado actual y futuro.",
        "Diagramas BPMN cuando sea adecuado.",
        "Matriz de responsabilidades.",
        "Análisis de cuellos de botella y riesgos.",
        "Procedimientos e instrucciones de trabajo.",
        "Criterios y niveles de decisión.",
        "Requisitos funcionales para sistemas.",
        "Indicadores de proceso.",
        "Plan de implementación.",
      ]},
      { type: "bullets", heading: "Aplicaciones frecuentes", items: [
        "Atención y recorrido del cliente.",
        "Elaboración y aprobación de propuestas.",
        "Compras y gestión de proveedores.",
        "Producción de eventos.",
        "Gestión de proyectos.",
        "Operación de programas sociales.",
        "Creación y publicación de contenido.",
        "Rendición de cuentas.",
      ]},
    ],
    ctaLabel: "Conversemos sobre sus procesos",
    ctaHref: "/contato",
  },

  "governanca-e-indicadores": {
    eyebrow: "GOBERNANZA E INDICADORES",
    title: "Decisión, responsabilidad y evidencia en el mismo sistema.",
    intro: "La gobernanza define quién decide, con base en qué información y dentro de qué límite. Los indicadores muestran qué necesita atención.",
    lead: "Cuando ambos elementos están desconectados, los informes se acumulan y los problemas siguen sin responsable. Estructuramos el sistema que une información a decisión y decisión a seguimiento.",
    parentLabel: "Gestión",
    parentHref: "/solucoes/gestao",
    blocks: [
      { type: "cards", heading: "Lo que estructuramos", items: [
        { title: "Arquitectura de gobernanza", description: "Roles, responsabilidades, foros, niveles de decisión, escalamiento y relación entre instancias." },
        { title: "Matriz de decisión", description: "Quién recomienda, aprueba, ejecuta, consulta y hace seguimiento a cada tema relevante." },
        { title: "Cadencia de gestión", description: "Reuniones, rituales, agendas, preparación, registros y seguimiento de decisiones." },
        { title: "Sistema de indicadores", description: "Objetivos, preguntas de gestión, métricas, fórmulas, fuentes, periodicidad y responsables." },
        { title: "Dashboards e informes", description: "Visualizaciones y síntesis adecuadas a quien opera, gestiona o patrocina." },
        { title: "Rendición de cuentas", description: "Organización de evidencias, entregas, resultados, riesgos, desvíos y aprendizajes." },
      ]},
      { type: "bullets", heading: "Entregables posibles", items: [
        "Mapa de gobernanza.",
        "Matriz RACI o equivalente.",
        "Reglamento de foros y comités.",
        "Matriz de niveles de decisión.",
        "Calendario de gestión.",
        "Árbol o catálogo de indicadores.",
        "Fichas técnicas de las métricas.",
        "Modelo de dashboard.",
        "Modelo de informe ejecutivo.",
        "Plan de implementación y adopción.",
      ]},
      { type: "bullets", heading: "Diferentes niveles de evidencia", intro: "Distinguimos actividad, entrega, alcance, resultado e impacto — para que el volumen de actividad nunca se presente como transformación comprobada.", items: [
        "Actividad: lo que se hizo.",
        "Entrega: lo que se produjo.",
        "Alcance: quién se vio involucrado.",
        "Resultado: lo que cambió de forma observable.",
        "Impacto: cambio atribuible o plausiblemente relacionado, según el método y la evidencia disponibles.",
      ]},
      { type: "bullets", heading: "Para proyectos, programas y operaciones", items: [
        "Proyectos corporativos.",
        "Programas de responsabilidad social.",
        "Portafolios y PMOs.",
        "Organizaciones sociales.",
        "Eventos y experiencias.",
        "Procesos recurrentes.",
        "Iniciativas de innovación.",
        "Alianzas con múltiples stakeholders.",
      ]},
    ],
    ctaLabel: "Conversemos sobre su gobernanza",
    ctaHref: "/contato",
  },

  operacoes: {
    eyebrow: "OPERACIONES",
    title: "Es en la ejecución donde el proyecto se decide.",
    intro: "Un buen plan necesita funcionar en el tiempo, el presupuesto y el territorio reales. Creation coordina personas, proveedores, recursos, permisos, traslados y decisiones para que cada frente avance con claridad hasta la entrega.",
    lead: "Actuamos como núcleo de operación o como extensión del equipo del cliente, con responsabilidad definida y seguimiento cercano.",
    parentLabel: "Soluciones",
    parentHref: "/solucoes",
    blocks: [
      { type: "bullets", heading: "Lo que coordinamos", items: [
        "Alcance operativo y criterios de entrega.",
        "Presupuesto, contrataciones y control de costos.",
        "Cronograma, hitos y secuenciación.",
        "Proveedores, equipos técnicos y socios.",
        "Infraestructura, equipos y materiales.",
        "Permisos, autorizaciones y requisitos locales.",
        "Logística de personas, cargas y recursos.",
        "Contingencias, cambios y comunicación de campo.",
      ]},
      { type: "bullets", heading: "Dónde entramos", intro: "Creation puede asumir toda la operación o un frente delimitado. También puede integrarse a estructuras ya existentes, incluyendo:", items: [
        "Equipos de marketing y comunicación.",
        "Productoras y agencias.",
        "Áreas de responsabilidad social y sostenibilidad.",
        "Organizaciones culturales y sociales.",
        "Productoras audiovisuales.",
        "Marcas, creators y proyectos independientes.",
      ]},
    ],
    childrenLabel: "Nuestros frentes de actuación",
    children: [
      { title: "Gestión de Eventos", description: "Planificación y coordinación del ciclo completo de eventos corporativos, culturales, institucionales, de innovación y de impacto.", href: "/operacoes/gestao-de-eventos" },
      { title: "Producción Ejecutiva", description: "Presupuesto, cronograma, proveedores, equipos, infraestructura y seguimiento de la realización, desde la preproducción hasta el cierre.", href: "/operacoes/producao-executiva" },
      { title: "Location & Fixer", description: "Investigación de locaciones, articulación local, permisos, apoyo a equipos y solución de necesidades de producción en Río de Janeiro y la Costa Verde.", href: "/operacoes/location-fixer-rio-de-janeiro" },
      { title: "Receptivo, Choferes & Locaciones", description: "Traslados, vehículos, choferes, hospedaje, espacios, equipos y soporte de llegada para equipos, invitados y producciones.", href: "/operacoes/receptivo-drivers-locacoes" },
    ],
    ctaLabel: "Presente su operación",
    ctaHref: "/contato",
  },

  "gestao-de-eventos": {
    eyebrow: "GESTIÓN DE EVENTOS",
    title: "Un evento empieza mucho antes del montaje.",
    intro: "Objetivo, público, experiencia, contenido, presupuesto y operación necesitan apuntar en la misma dirección.",
    lead: "Creation estructura y coordina eventos desde el concepto hasta el cierre, conectando decisión estratégica y realización.",
    parentLabel: "Operaciones",
    parentHref: "/operacoes",
    blocks: [
      { type: "steps", heading: "El ciclo completo", items: [
        { number: "01", title: "Concepto y objetivos", description: "Definición del rol del evento, públicos, propuesta de valor, resultados esperados y criterios de éxito." },
        { number: "02", title: "Arquitectura de la experiencia", description: "Formato, programación, recorrido del participante, ambientes, flujos, activaciones y puntos de contacto." },
        { number: "03", title: "Planificación", description: "Alcance, presupuesto, cronograma, gobernanza, proveedores, riesgos, permisos y plan operativo." },
        { number: "04", title: "Producción", description: "Infraestructura, audiovisual, escenografía, alimentación, equipos, materiales, logística, montaje y pruebas." },
        { number: "05", title: "Realización y cierre", description: "Coordinación general, operación de sala o escenario, desmontaje, conciliación, datos e informe." },
      ]},
      { type: "bullets", heading: "Eventos que podemos estructurar y realizar", items: [
        "Encuentros corporativos e institucionales.",
        "Conferencias, foros y seminarios.",
        "Hackathons y programas de innovación.",
        "Eventos culturales y de economía creativa.",
        "Activaciones de marca y live marketing.",
        "Eventos de responsabilidad social e impacto.",
        "Transmisiones en vivo y formatos híbridos.",
      ]},
      { type: "bullets", heading: "Entregables posibles", items: [
        "Concepto y diseño del evento.",
        "Plan maestro y cronograma.",
        "Presupuesto y mapa de contrataciones.",
        "Matriz de responsabilidades.",
        "Programación y guion técnico.",
        "Plan de espacios, flujos y accesos.",
        "Plan de riesgos y contingencias.",
        "Operación de acreditación.",
        "Informe de ejecución e indicadores.",
      ]},
    ],
    ctaLabel: "Planifique su evento",
    ctaHref: "/contato",
  },

  "producao-executiva": {
    eyebrow: "PRODUCCIÓN EJECUTIVA",
    title: "La producción ejecutiva es transformar muchas dependencias en una entrega.",
    intro: "Cuando el proyecto necesita salir del papel, cada contratación, plazo, acceso y decisión empieza a afectar al conjunto.",
    lead: "Creation organiza esas dependencias y coordina la realización con visión de presupuesto, cronograma, calidad y riesgo.",
    parentLabel: "Operaciones",
    parentHref: "/operacoes",
    blocks: [
      { type: "bullets", heading: "Dónde actuamos", items: [
        "Eventos corporativos, culturales e institucionales.",
        "Campañas y activaciones de marca.",
        "Proyectos de innovación y economía creativa.",
        "Programas sociales y territoriales.",
        "Grabaciones, contenidos y producciones audiovisuales.",
        "Ferias, exposiciones y experiencias.",
        "Proyectos especiales con múltiples socios.",
      ]},
      { type: "cards", heading: "Lo que puede incluir la producción ejecutiva", items: [
        { title: "Planificación de producción", description: "Descomposición del alcance, cronograma, presupuesto, mapa de recursos, secuencia de trabajo y puntos de decisión." },
        { title: "Presupuestos y contrataciones", description: "Solicitud y comparación de propuestas, equiparación técnica y comercial, apoyo a la contratación y control de compromisos." },
        { title: "Proveedores y equipos", description: "Selección, briefing, integración, seguimiento, validación de entregas y gestión de las interfaces." },
        { title: "Infraestructura y logística", description: "Espacios, equipos, materiales, transportes, hospedaje, alimentación, accesos, cargas y devoluciones." },
        { title: "Permisos y requisitos", description: "Mapeo de autorizaciones, documentos, seguros y responsabilidades técnicas aplicables." },
        { title: "Operación de campo", description: "Montaje, pruebas, paso de sonido, realización, desmontaje, control de incidencias y comunicación entre los frentes." },
      ]},
      { type: "bullets", heading: "Controles que sostienen la entrega", items: [
        "Presupuesto base y proyección de cierre.",
        "Cronograma de producción.",
        "Mapa de proveedores y contratos.",
        "Matriz de responsabilidades.",
        "Control de aprobaciones y cambios.",
        "Lista de equipos y materiales.",
        "Plan de accesos y acreditación.",
        "Mapa de riesgos y contingencias.",
        "Informe de incidencias y cierre.",
      ]},
      { type: "bullets", heading: "Cómo nos integramos al equipo", items: [
        "Producción completa — Creation responde por la planificación y la coordinación del conjunto definido en el contrato.",
        "Frente específico — asumimos una parte delimitada, como logística, proveedores, producción local u operación de campo.",
        "Refuerzo temporal — entramos como extensión de la agencia, productora, marca u organización durante una etapa crítica.",
      ]},
    ],
    ctaLabel: "Conversemos sobre su producción",
    ctaHref: "/contato",
  },

  "location-fixer-rio-de-janeiro": {
    eyebrow: "LOCATION & FIXER",
    title: "Usted llega con el proyecto. La operación local ya conoce el camino.",
    intro: "Locaciones, autorizaciones, accesos, equipos y traslados cambian de un territorio a otro.",
    lead: "Creation ofrece investigación de locaciones y soporte de producción local para equipos que necesitan realizar filmaciones, campañas, eventos y proyectos en Río de Janeiro y la Costa Verde.",
    parentLabel: "Operaciones",
    parentHref: "/operacoes",
    blocks: [
      { type: "cards", heading: "Dos servicios que se complementan", items: [
        { title: "Location", description: "Investigación y viabilización de espacios compatibles con la propuesta creativa, las necesidades técnicas, el presupuesto y la logística de la producción." },
        { title: "Fixer", description: "Articulación local para transformar el briefing en una operación posible, conectando información, personas, proveedores, requisitos y decisiones en el territorio." },
      ]},
      { type: "bullets", heading: "Servicios de location", items: [
        "Lectura del briefing creativo y técnico.",
        "Investigación inicial de opciones.",
        "Scouting presencial, según el alcance.",
        "Fotos, videos e información operativa.",
        "Análisis de acceso, ruido, energía, apoyo y circulación.",
        "Interfaz con propietarios, administradores y órganos responsables.",
        "Apoyo a la negociación y documentación.",
        "Coordinación de visitas técnicas.",
      ]},
      { type: "bullets", heading: "Servicios de fixer", items: [
        "Investigación local y relevamiento de información.",
        "Indicación y coordinación de proveedores.",
        "Articulación con comunidades, instituciones y agentes locales.",
        "Apoyo a permisos, autorizaciones y documentos.",
        "Contratación de equipos y recursos, según el modelo definido.",
        "Producción de campo y seguimiento de agenda.",
        "Traducción cultural y orientación operativa.",
        "Logística, seguridad y planes de traslado.",
      ]},
      { type: "bullets", heading: "Para qué proyectos", items: [
        "Publicidad y campañas de marca.",
        "Cine, series, documentales y televisión.",
        "Fotografía y contenido digital.",
        "Creators y equipos internacionales.",
        "Eventos, experiencias y activaciones.",
        "Investigación de campo y proyectos institucionales.",
      ]},
    ],
    ctaLabel: "Envíe su briefing",
    ctaHref: "/contato",
  },

  "receptivo-drivers-locacoes": {
    eyebrow: "RECEPTIVO, CHOFERES & LOCACIONES",
    title: "La logística empieza antes de la llegada.",
    intro: "Equipos, invitados y recursos necesitan estar en el lugar correcto, a la hora correcta y con información suficiente para seguir el plan.",
    lead: "Creation coordina la logística de llegada, permanencia y traslado para producciones, eventos y proyectos especiales.",
    parentLabel: "Operaciones",
    parentHref: "/operacoes",
    blocks: [
      { type: "cards", heading: "Lo que podemos coordinar", items: [
        { title: "Llegadas y salidas", description: "Recepción en aeropuertos, terminales, hoteles, bases de producción y otros puntos definidos." },
        { title: "Transfers y choferes", description: "Choferes, vehículos ejecutivos, vans, buses, utilitarios y otros recursos compatibles con el traslado." },
        { title: "Rutas y agendas", description: "Planificación de trayectos, ventanas de salida, puntos de encuentro, tiempo de margen y actualizaciones operativas." },
        { title: "Hospedaje y bases", description: "Investigación y coordinación de hoteles, casas, apartamentos, salas de apoyo, camerinos y bases operativas." },
        { title: "Locaciones de recursos", description: "Vehículos, equipos, mobiliario, estructuras, comunicación, apoyo y otros ítems previstos en el alcance." },
        { title: "Soporte de permanencia", description: "Información de servicio, seguimiento de invitados, apoyo de producción y solución de necesidades durante la agenda." },
      ]},
      { type: "bullets", heading: "Para quién", items: [
        "Equipos de filmación y fotografía.",
        "Invitados, ponentes y ejecutivos.",
        "Artistas, creators e influencers.",
        "Equipos de marcas, agencias y productoras.",
        "Delegaciones y grupos institucionales.",
        "Equipos técnicos y proveedores.",
      ]},
      { type: "bullets", heading: "Información que organizamos", items: [
        "Nombres, contactos y responsables.",
        "Vuelos, horarios y puntos de llegada.",
        "Hospedajes y direcciones.",
        "Agenda consolidada.",
        "Vehículos, capacidad y equipaje.",
        "Credenciales, accesos y autorizaciones.",
        "Contactos de emergencia y escalamiento.",
        "Plan alternativo para atrasos y cambios.",
      ]},
    ],
    ctaLabel: "Planifique su logística",
    ctaHref: "/contato",
  },

  inovacao: {
    eyebrow: "INNOVACIÓN",
    title: "Las ideas ganan valor cuando se convierten en proyectos.",
    intro: "La innovación no empieza en una dinámica ni termina en una presentación. Necesita un problema relevante, criterios de decisión, personas movilizadas y un camino para probar, aprender e implementar.",
    lead: "Creation estructura y realiza iniciativas de innovación conectadas a la estrategia y a la capacidad real de la organización.",
    image: { src: "/images/blockchain-rio.webp", alt: "Blockchain Rio — evento de innovación realizado por Creation" },
    parentLabel: "Soluciones",
    parentHref: "/solucoes",
    blocks: [
      { type: "cards", heading: "Frentes de actuación", items: [
        { title: "Estrategia de innovación", description: "Lectura de contexto, definición de temas prioritarios, objetivos, portafolio, gobernanza e indicadores." },
        { title: "Diseño de desafíos", description: "Formulación del problema, preguntas orientadoras, criterios, públicos, datos y condiciones de participación." },
        { title: "Programas y jornadas", description: "Estructuración de hackathons, laboratorios, sprints, convocatorias, ciclos de ideación, aceleración e innovación abierta." },
        { title: "Facilitación y contenido", description: "Talleres, encuentros, mentorías, curaduría, materiales y conducción de procesos colaborativos." },
        { title: "Experimentación", description: "Hipótesis, prototipos, planes de prueba, criterios de validación y registro de aprendizajes." },
        { title: "Implementación", description: "Transformación de las soluciones seleccionadas en proyectos, con responsables, recursos, cronograma y gobernanza." },
      ]},
      { type: "bullets", heading: "Preguntas que organizan un programa", items: [
        "¿Qué problema necesita resolverse y por qué ahora?",
        "¿Qué ya se sabe y qué todavía necesita investigarse?",
        "¿Quién vive el problema y quién puede decidir sobre la solución?",
        "¿Qué restricciones no pueden ignorarse?",
        "¿Cómo se compararán las propuestas?",
        "¿Qué recursos existirán para probar e implementar?",
        "¿Quién asume la continuidad después del programa?",
      ]},
      { type: "steps", heading: "Cómo trabajamos", items: [
        { number: "01", title: "Investigar", description: "Contexto, problema, públicos, restricciones y evidencias." },
        { number: "02", title: "Diseñar", description: "Formato, recorrido, gobernanza, criterios, recursos y comunicación." },
        { number: "03", title: "Movilizar", description: "Participantes, especialistas, socios, mentores y tomadores de decisión." },
        { number: "04", title: "Realizar", description: "Contenido, facilitación, operación, registro y seguimiento." },
        { number: "05", title: "Desdoblar", description: "Selección, pilotos, proyectos, aprendizajes y próximos pasos." },
      ]},
      { type: "bullets", heading: "Entregables posibles", items: [
        "Diagnóstico de innovación.",
        "Tesis o agenda de prioridades.",
        "Mapa de oportunidades.",
        "Arquitectura de programa.",
        "Reglamento y criterios de selección.",
        "Plan de movilización.",
        "Recorrido de participantes.",
        "Backlog de hipótesis y experimentos.",
        "Plan de pilotos.",
        "Modelo de gobernanza.",
        "Informe de resultados y recomendaciones.",
      ]},
    ],
    ctaLabel: "Conversemos sobre su desafío",
    ctaHref: "/contato",
  },

  impacto: {
    eyebrow: "IMPACTO",
    title: "Impacto que se construye y se comprueba.",
    intro: "La intención social no reemplaza la estrategia, la gestión ni la evidencia. Creation ayuda a empresas, organizaciones y socios a transformar compromisos en programas estructurados.",
    lead: "Con públicos definidos, responsabilidades claras y seguimiento compatible con lo que se pretende cambiar.",
    image: { src: "/images/impacto-artesanato.webp", alt: "Feria de artesanía local, parte de un programa de impacto realizado por Creation" },
    parentLabel: "Soluciones",
    parentHref: "/solucoes",
    blocks: [
      { type: "cards", heading: "Frentes de actuación", items: [
        { title: "Diagnóstico social y territorial", description: "Lectura de contexto, públicos, activos, vulnerabilidades, actores, iniciativas existentes, datos y brechas de conocimiento." },
        { title: "Estrategia de impacto", description: "Definición de prioridades, públicos, objetivos, principios, criterios y relación con la estrategia de la organización." },
        { title: "Teoría de cambio", description: "Organización de las relaciones esperadas entre recursos, actividades, entregas, resultados e impactos, incluyendo premisas y factores externos." },
        { title: "Diseño de programas", description: "Alcance, recorrido de los participantes, socios, gobernanza, presupuesto, cronograma, riesgos e indicadores." },
        { title: "Gestión y operación", description: "Coordinación de equipos, socios, territorios, proveedores, decisiones y entregas." },
        { title: "Monitoreo y evaluación", description: "Preguntas evaluativas, indicadores, fuentes, instrumentos, análisis, limitaciones y comunicación de resultados." },
      ]},
      { type: "bullets", heading: "Lo que diferenciamos", intro: "Esta distinción reduce el riesgo de comunicar el volumen de ejecución como si fuera transformación comprobada.", items: [
        "Insumo: recurso utilizado.",
        "Actividad: acción realizada.",
        "Entrega: producto o servicio disponibilizado.",
        "Alcance: personas u organizaciones involucradas.",
        "Resultado: cambio observado en el público o sistema.",
        "Impacto: cambio de mayor alcance o duración, analizado con atención a la contribución, la atribución y el contexto.",
      ]},
      { type: "bullets", heading: "Entregables posibles", items: [
        "Diagnóstico o línea de base.",
        "Mapa de stakeholders.",
        "Estrategia de actuación.",
        "Teoría de cambio.",
        "Diseño de programa.",
        "Matriz lógica.",
        "Plan de implementación.",
        "Modelo de gobernanza.",
        "Matriz de riesgos.",
        "Plan de monitoreo y evaluación.",
        "Catálogo de indicadores.",
        "Panel o informe.",
        "Evaluación de resultados.",
      ]},
    ],
    childrenLabel: "Especialidad relacionada",
    children: [
      { title: "Marketing de Causa", description: "Estrategia que conecta marca, causa y acción, con alianza, gobernanza, experiencia y comunicación responsable.", href: "/impacto/marketing-de-causa" },
    ],
    ctaLabel: "Conversemos sobre su iniciativa",
    ctaHref: "/contato",
  },

  "marketing-de-causa": {
    eyebrow: "MARKETING DE CAUSA",
    title: "Una causa no puede ser solo una campaña.",
    intro: "Cuando una marca se asocia a una cuestión social, asume responsabilidad sobre lo que promete, cómo actúa y a quién involucra.",
    lead: "Creation estructura iniciativas que conectan posicionamiento, alianza, experiencia y entrega concreta.",
    parentLabel: "Impacto",
    parentHref: "/impacto",
    blocks: [
      { type: "cards", heading: "Lo que estructuramos", items: [
        { title: "Adherencia entre marca y causa", description: "Análisis de historia, valores, actuación, públicos, riesgos y contribución posible." },
        { title: "Estrategia de la iniciativa", description: "Objetivo, públicos, propuesta, tesis de actuación, resultados esperados y criterios de decisión." },
        { title: "Mapeo y alianza", description: "Identificación, evaluación y construcción de la relación con organizaciones, especialistas, territorios y redes." },
        { title: "Concepto y experiencia", description: "Traducción de la estrategia en programa, campaña, contenido, evento, activación o recorrido de engagement." },
        { title: "Gobernanza", description: "Roles, aprobaciones, uso de imagen, recursos, integridad, seguimiento y respuesta a riesgos." },
        { title: "Realización y evidencia", description: "Producción, gestión, indicadores, registros, rendición de cuentas y aprendizajes." },
      ]},
      { type: "bullets", heading: "Formatos posibles", items: [
        "Campañas vinculadas a una acción concreta.",
        "Programas de engagement de clientes o colaboradores.",
        "Activaciones y experiencias con propósito.",
        "Eventos, encuentros y movilizaciones.",
        "Productos o ediciones especiales.",
        "Donaciones asociadas a ventas, con reglas transparentes.",
        "Plataformas de contenido y educación.",
        "Alianzas territoriales.",
      ]},
      { type: "bullets", heading: "Preguntas que necesitan respuesta", items: [
        "¿Por qué esta marca debe actuar en esta causa?",
        "¿Qué necesidad concreta será enfrentada?",
        "¿Quién participa en las decisiones?",
        "¿Qué organización tiene legitimidad y capacidad en el tema?",
        "¿Qué se entregará, a quién y en qué período?",
        "¿Qué sucede cuando termina la campaña?",
      ]},
      { type: "bullets", heading: "Entregables posibles", items: [
        "Análisis de adherencia y riesgo.",
        "Mapa de causas y oportunidades.",
        "Estrategia y narrativa central.",
        "Mapa de stakeholders.",
        "Criterios para selección de socios.",
        "Diseño de programa o campaña.",
        "Modelo de gobernanza.",
        "Plan de movilización y contenido.",
        "Matriz de indicadores.",
        "Protocolo de transparencia.",
      ]},
    ],
    ctaLabel: "Conversemos sobre su iniciativa",
    ctaHref: "/contato",
  },

  "branding-experiencias": {
    eyebrow: "BRANDING & EXPERIENCIAS",
    title: "Estrategia que puede verse, vivirse y recordarse.",
    intro: "Una marca se vuelve concreta en los encuentros que produce. Creation conecta posicionamiento, concepto y operación para crear experiencias coherentes con lo que la organización quiere representar.",
    lead: "Y capaces de funcionar en el mundo real.",
    image: { src: "/images/reservax-lounge.webp", alt: "Activación de marca ReservaX Lounge, producida por Creation" },
    parentLabel: "Soluciones",
    parentHref: "/solucoes",
    blocks: [
      { type: "cards", heading: "Frentes de actuación", items: [
        { title: "Estrategia de marca", description: "Posicionamiento, propuesta de valor, públicos, mensajes, territorios de expresión y criterios de coherencia." },
        { title: "Concepto creativo", description: "Idea central, narrativa, lenguaje, experiencia y posibles desdoblamientos." },
        { title: "Experiencia de marca", description: "Recorrido, puntos de contacto, interacciones, ambientes, contenido, servicios y comportamiento del equipo." },
        { title: "Activaciones y live marketing", description: "Diseño y realización de acciones presenciales, híbridas o itinerantes." },
        { title: "Eventos y encuentros", description: "Formatos propios, lanzamientos, comunidades, experiencias para públicos internos y externos." },
        { title: "Contenido y alianzas", description: "Curaduría, creators, especialistas, organizaciones, territorios y redes compatibles con la propuesta." },
      ]},
      { type: "bullets", heading: "Experiencias que pueden estructurarse", items: [
        "Activaciones de marca.",
        "Lanzamientos y encuentros propios.",
        "Experiencias culturales.",
        "Acciones de relacionamiento.",
        "Programas para comunidades.",
        "Ferias, muestras y espacios de marca.",
        "Experiencias para colaboradores.",
        "Campañas con presencia territorial.",
      ]},
      { type: "bullets", heading: "Lo que necesita permanecer coherente", items: [
        "Promesa — lo que la marca afirma y qué expectativa crea.",
        "Participación — lo que el público puede hacer, sentir, aprender o llevarse.",
        "Operación — cómo el espacio, el equipo, la fila, el acceso, el contenido, la atención y la tecnología sostienen la experiencia.",
        "Continuidad — qué sucede después del encuentro y cómo puede continuar la relación.",
      ]},
      { type: "bullets", heading: "Entregables posibles", items: [
        "Diagnóstico de marca y contexto.",
        "Posicionamiento o plataforma de mensajes.",
        "Concepto y narrativa de la experiencia.",
        "Arquitectura de recorrido.",
        "Plan de puntos de contacto.",
        "Briefing creativo y de producción.",
        "Curaduría de contenido y socios.",
        "Plan de activación.",
        "Presupuesto y cronograma.",
        "Indicadores e informe.",
      ]},
    ],
    ctaLabel: "Conversemos sobre su marca",
    ctaHref: "/contato",
  },

  "como-trabalhamos": {
    eyebrow: "CÓMO TRABAJAMOS",
    title: "Entender. Estructurar. Realizar. Comprobar.",
    intro: "Proyectos diferentes exigen equipos, herramientas y recorridos diferentes. Lo que permanece es una forma disciplinada de transformar una necesidad en dirección, estructura, entrega y evidencia.",
    lead: "No llamamos a este enfoque metodología propietaria. El valor está en elegir y aplicar el método adecuado a cada decisión, no en inventar nombres para etapas conocidas.",
    blocks: [
      { type: "bullets", heading: "El recorrido no necesita comenzar por el inicio", items: [
        "Un desafío todavía difuso puede empezar por Entender.",
        "Una iniciativa aprobada puede empezar por Estructurar.",
        "Un proyecto planificado puede necesitar Realizar.",
        "Una entrega concluida puede necesitar Comprobar.",
      ]},
      { type: "bullets", heading: "Responsabilidades claras antes de la ejecución", intro: "Cada propuesta debe definir:", items: [
        "Lo que Creation asume.",
        "Lo que permanece con el cliente.",
        "Qué decisiones dependen de terceros.",
        "Qué entregas se producirán.",
        "Cómo se aprobarán los cambios.",
        "Qué datos serán necesarios.",
        "Cuándo se considerará concluido el trabajo.",
        "La claridad contractual no burocratiza el proyecto. Protege el ritmo de la ejecución.",
      ]},
      { type: "bullets", heading: "Herramientas al servicio del proyecto", intro: "SWOT, PESTEL, BPMN, Canvas, Design Thinking, Lean, Kanban, Scrum, RACI, OKRs y otras herramientas pueden utilizarse cuando ayudan a responder una pregunta real. No aplicamos una herramienta porque sea conocida o porque produzca un diagrama bonito — elegimos el recurso por el problema, la madurez del equipo y la decisión que necesita tomarse.", items: ["SWOT y PESTEL", "BPMN y Canvas", "Design Thinking y Lean", "Kanban y Scrum", "RACI y OKRs"] },
    ],
    childrenLabel: "Las cuatro etapas",
    children: [
      { title: "01 — Entender", description: "Antes de proponer una solución, investigamos el contexto en el que el proyecto necesita existir: qué necesidad dio origen al pedido, quién decide, participa, se ve afectado o puede bloquear el avance, qué restricciones de plazo, presupuesto, territorio y capacidad existen, qué ya se intentó y qué se aprendió, y qué resultado necesita alcanzarse o demostrarse. Pueden utilizarse entrevistas, análisis documental, investigación de mercado, escucha de públicos, datos secundarios, observación de campo, benchmarking y mapeo de stakeholders. El resultado es una lectura compartida del desafío, de las preguntas que necesitan respuesta y de los criterios que orientarán el resto del trabajo.", href: "/contato" },
      { title: "02 — Estructurar", description: "Transformamos el entendimiento en un proyecto que pueda decidirse, financiarse, gestionarse y ejecutarse: objetivos, alcance y prioridades, entregas y criterios de aceptación, gobernanza y responsabilidades, equipo, socios y proveedores, presupuesto, cronograma y dependencias, riesgos, premisas y decisiones pendientes, e indicadores y formas de seguimiento. El resultado es el plan de proyecto, la arquitectura de gobernanza, el presupuesto, el cronograma, el mapa de riesgos, la estrategia de movilización y el sistema inicial de indicadores, según el alcance contratado.", href: "/contato" },
      { title: "03 — Realizar", description: "Ponemos la estructura en movimiento, coordinando personas, decisiones y recursos hasta la entrega: mantenemos una cadencia clara de decisión y seguimiento, coordinamos equipos internos, socios y proveedores, registramos cambios de alcance y sus impactos, seguimos presupuesto, plazo, riesgos y calidad, resolvemos dependencias e impedimentos, y ajustamos el recorrido sin perder el objetivo del proyecto. El resultado son entregas realizadas, decisiones registradas, riesgos tratados y una operación seguida de forma transparente.", href: "/contato" },
      { title: "04 — Comprobar", description: "El cierre no es solo el momento de declarar que algo fue entregado. Es cuando organizamos las evidencias disponibles y evaluamos lo que el proyecto efectivamente produjo: consolidamos entregas, datos y registros, comparamos ejecución, metas y criterios definidos, analizamos resultados y limitaciones, documentamos aprendizajes y recomendaciones, y orientamos la continuidad, la próxima edición o el cierre. El resultado es un informe, panel, presentación ejecutiva, rendición de cuentas, lecciones aprendidas u otro formato de evidencia adecuado al proyecto. \"Comprobar\" no significa atribuir al proyecto resultados que los datos no sostienen: cuando no sea posible demostrar causalidad, distinguimos entrega, resultado observado e hipótesis de impacto.", href: "/contato" },
    ],
    ctaLabel: "Cuéntenos su proyecto",
    ctaHref: "/contato",
  },
};

export const homeCapacidades: HomeCapacidade[] = [
  {
    title: "Estrategia",
    tagline: "Claridad para decidir.",
    description: "Investigamos el contexto, organizamos la información y transformamos la complejidad en dirección. La estrategia define el problema, orienta las decisiones y construye un camino viable para el proyecto.",
    items: ["Inteligencia de Mercado", "Diagnóstico y Planificación", "Estructuración y Viabilización de Proyectos"],
    href: "/solucoes/estrategia",
    linkLabel: "Conozca Estrategia",
  },
  {
    title: "Gestión",
    tagline: "Ritmo para avanzar.",
    description: "Transformamos dirección en alcance, responsabilidades y decisiones. Estructuramos gobernanza, equipos, procesos e indicadores para que el proyecto avance con ritmo, control y transparencia.",
    items: ["Gestión de Proyectos y PMO", "Gestión de Procesos de Negocio", "Gobernanza, Indicadores y Riesgos"],
    href: "/solucoes/gestao",
    linkLabel: "Conozca Gestión",
  },
  {
    title: "Operaciones",
    tagline: "Ejecución para realizar.",
    description: "Movilizamos personas, socios, proveedores, logística, espacios y recursos para transformar la planificación en entrega, coordinando la operación desde la preparación hasta el cierre.",
    items: ["Gestión y Producción de Eventos", "Producción Ejecutiva y Logística", "Location & Fixer", "Receptivo, Choferes y Locaciones"],
    href: "/operacoes",
    linkLabel: "Conozca Operaciones",
  },
];

export const homeEspecialidades: HomeEspecialidade[] = [
  {
    title: "Innovación",
    tagline: "Las ideas ganan valor cuando se convierten en proyectos.",
    description: "Estructuramos y realizamos programas de innovación, desafíos, hackathons, ideathons y jornadas.",
    href: "/inovacao",
    linkLabel: "Conozca Innovación",
    image: { src: "/images/hacking-rio.webp", alt: "Hacking.Rio — programa de innovación realizado por Creation" },
  },
  {
    title: "Impacto",
    tagline: "Impacto que se construye y se comprueba.",
    description: "Diseñamos, gestionamos y realizamos programas de responsabilidad social, marketing de causa y desarrollo territorial.",
    href: "/impacto",
    linkLabel: "Conozca Impacto",
    image: { src: "/images/impacto-hero.webp", alt: "Programa de impacto social en territorio, realizado por Creation" },
  },
  {
    title: "Branding & Experiencias",
    tagline: "Estrategia que puede verse, vivirse y recordarse.",
    description: "Transformamos posicionamiento en identidad, narrativa, contenido, activaciones y experiencias.",
    href: "/branding-experiencias",
    linkLabel: "Conozca Branding & Experiencias",
    image: { src: "/images/reservax-lounge.webp", alt: "Activación de marca ReservaX Lounge, producida por Creation" },
  },
];

export const homeSolucoes: HomeSolucao[] = [
  {
    title: "Creation Ops Rio",
    description: "Operación local integrada para agencias, productoras, marcas y equipos que realizan proyectos en Río de Janeiro. Location, fixer, receptivo, choferes, locaciones, proveedores y logística bajo una única coordinación.",
    href: "/creator-ops-rio",
  },
];

export const casesStub: CaseStub[] = [
  {
    title: "Hacking.Rio",
    client: "Íons Innovation",
    context: "Producción y operación ejecutiva de cuatro ediciones en tres formatos diferentes (presencial, digital y metaverso), integrando participantes, mentores, socios y proveedores.",
    numbers: ["4 ediciones", "3 formatos", "+5 mil competidores", "+170 mil personas alcanzadas"],
  },
  {
    title: "Hacking.Help",
    client: "Íons Innovation",
    context: "Concepción y producción ejecutiva de una maratón en línea creada rápidamente para mantener la movilización de propósito social durante la pandemia.",
    numbers: ["1.533 competidores", "5 países de habla portuguesa", "R$500 mil en medios espontáneos estimados"],
  },
  {
    title: "HR Talks",
    client: "Íons Innovation",
    context: "Producción ejecutiva de una programación digital internacional de larga duración, coordinando agenda, ponentes y transmisión en vivo.",
    numbers: ["15.500 inscritos", "172 ponentes globales", "40 horas de contenido en vivo"],
  },
  {
    title: "Pertinho de Casa — Escuela y Ferias",
    client: "Rede Asta y Porto Sudeste",
    context: "Coordinación territorial de una escuela de negocios y ferias de comercialización para fortalecer a emprendedores locales.",
    numbers: ["2 frentes de actuación", "6 eventos de comercialización", "R$19.649 en ventas acompañadas"],
    note: "La evaluación de impacto fue realizada por Rede Asta. Los números presentados describen entregas y resultados comerciales informados para el período, no una atribución integral de impacto a Creation.",
  },
  {
    title: "Pertinho de Casa — Plataforma",
    client: "Rede Asta y Porto Sudeste",
    context: "Reclutamiento de vendedores, articulación del Comité por la Economía Local y seguimiento trimestral de la plataforma.",
    numbers: ["241 emprendedores", "56 barrios de Itaguaí y Seropédica", "R$30.650,11 en facturación registrada"],
    note: "El crecimiento quedó por debajo de la proyección inicial indicada en los materiales. La evaluación de impacto fue realizada por Rede Asta. Registrar esta diferencia es importante porque un case también debe mostrar lo que la ejecución enseñó y qué hipótesis necesitan revisarse.",
  },
  {
    title: "World Creativity Day",
    client: "Centro Cultural Banco do Brasil Río de Janeiro",
    context: "Concepción y ejecución de programación presencial y en línea sobre creatividad, distribuida en diferentes espacios y días.",
    numbers: ["3 días de programación", "2 espacios", "+1 mil personas alcanzadas", "+50 inspiradores en línea"],
  },
];
