import type { StubPageData, HomeCapacidade, HomeEspecialidade, HomeSolucao, CaseStub } from "./types";

export const stubData: Record<string, StubPageData> = {
  solucoes: {
    eyebrow: "SOLUÇÕES",
    title: "Soluções que começam pelo desafio, não pelo catálogo.",
    intro:
      "A Creation combina estratégia, gestão e capacidade operacional de acordo com o contexto, o momento e a estrutura de cada projeto.",
    lead: "Podemos assumir uma frente específica ou conectar todo o percurso, do entendimento inicial à entrega e à análise dos resultados.",
    blocks: [
      {
        type: "cards",
        heading: "Comece pelo que precisa acontecer",
        intro: "Você não precisa conhecer o vocabulário de uma consultoria para encontrar a solução certa. O ponto de partida é reconhecer o que está impedindo o projeto de avançar.",
        items: [
          { title: "Preciso entender e decidir", description: "Inteligência de mercado, pesquisa, diagnóstico, planejamento e definição de prioridades." },
          { title: "Preciso estruturar e viabilizar", description: "Estruturação de projetos, modelagem, planejamento de recursos e estratégia de viabilização." },
          { title: "Preciso organizar e gerir", description: "Gestão de projetos e PMO, gestão de processos, governança, indicadores e coordenação de equipes." },
          { title: "Preciso executar e operar", description: "Gestão de eventos, produção executiva, location services, fixer, receptivo, drivers e locações." },
          { title: "Preciso mobilizar pessoas e públicos", description: "Inovação, programas de impacto, marketing de causa, branding, ativações e experiências." },
          { title: "Preciso medir e demonstrar", description: "Desenho de indicadores, governança de dados, avaliação, relatórios e mensuração de impacto ou eventos." },
        ],
      },
      {
        type: "bullets",
        heading: "Diferentes formas de trabalhar conosco",
        items: [
          "Projeto integrado — a Creation conecta estratégia, gestão e operação e responde pelo percurso completo definido em contrato.",
          "Frente específica — assumimos uma etapa ou competência delimitada, integrada à estrutura já existente do cliente.",
          "Extensão da equipe — acrescentamos capacidade temporária de gestão, produção ou coordenação a equipes internas, agências e produtoras.",
        ],
      },
    ],
    childrenLabel: "Capacidades e especialidades",
    children: [
      { title: "Estratégia", description: "Clareza para decidir: inteligência de mercado, diagnóstico e planejamento, estruturação e viabilização de projetos.", href: "/solucoes/estrategia" },
      { title: "Gestão", description: "Ritmo para avançar: gestão de projetos e PMO, processos de negócio, governança e indicadores.", href: "/solucoes/gestao" },
      { title: "Operações", description: "Execução para realizar: gestão de eventos, produção executiva, location & fixer, receptivo e logística.", href: "/operacoes" },
      { title: "Inovação", description: "Projetos, programas, hackathons e jornadas para transformar desafios em soluções aplicáveis.", href: "/inovacao" },
      { title: "Impacto", description: "Programas de responsabilidade social, desenvolvimento territorial e mensuração de resultados.", href: "/impacto" },
      { title: "Branding & Experiências", description: "Estratégia de marca, narrativa, ativações e experiências que conectam posicionamento e presença.", href: "/branding-experiencias" },
      { title: "Creation Ops Rio", description: "Operação local integrada no Rio de Janeiro para agências, produtoras, marcas e equipes internacionais.", href: "/creator-ops-rio" },
    ],
    ctaLabel: "Conte seu projeto",
    ctaHref: "/contato",
  },

  estrategia: {
    eyebrow: "ESTRATÉGIA",
    title: "Clareza antes da ação.",
    intro: "Investigamos o contexto, organizamos as informações e estruturamos as escolhas que permitem ao projeto avançar com direção.",
    lead: "Estratégia, para a Creation, não é um documento isolado da execução. É a definição do que precisa acontecer, por que esse caminho faz sentido e quais condições tornarão a realização possível.",
    parentLabel: "Soluções",
    parentHref: "/solucoes",
    blocks: [
      { type: "bullets", heading: "Quando a Estratégia é o ponto de entrada", items: [
        "Existe uma oportunidade, mas ainda não uma decisão estruturada.",
        "Há muitas informações e opiniões, mas falta uma leitura comum.",
        "A organização precisa compreender mercado, público ou concorrência.",
        "Uma ideia precisa se transformar em projeto viável.",
        "O investimento é relevante e as premissas ainda são frágeis.",
        "Áreas diferentes precisam concordar sobre objetivo, prioridade e caminho.",
        "Um projeto travou e é necessário revisar o problema antes de acelerar novamente.",
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", intro: "Conforme o escopo, a frente de Estratégia pode produzir:", items: [
        "Relatório de pesquisa e inteligência.",
        "Diagnóstico organizacional, mercadológico ou de projeto.",
        "Cenários e critérios de decisão.",
        "Definição de públicos e stakeholders.",
        "Proposta de valor ou tese de atuação.",
        "Objetivos, prioridades e roadmap.",
        "Modelo inicial do projeto.",
        "Plano de ação.",
        "Mapa de riscos e premissas.",
        "Apresentação executiva para decisão.",
      ]},
      { type: "bullets", heading: "Onde essa capacidade é aplicada", intro: "A Estratégia pode ser mobilizada em projetos de:", items: [
        "Inovação.",
        "Responsabilidade social e impacto.",
        "Branding e experiências.",
        "Eventos e ativações.",
        "Expansão de PMEs.",
        "Economia criativa.",
        "Processos e transformação organizacional.",
        "Projetos territoriais.",
      ]},
    ],
    childrenLabel: "O que podemos assumir",
    children: [
      { title: "Inteligência de Mercado", description: "Pesquisa e análise para compreender mercado, concorrência, públicos, tendências, riscos e oportunidades antes de decidir.", href: "/solucoes/inteligencia-de-mercado" },
      { title: "Diagnóstico e Planejamento", description: "Leitura estruturada da situação atual, definição do problema, prioridades, objetivos e plano de ação.", href: "/solucoes/diagnostico-e-planejamento" },
      { title: "Estruturação e Viabilização de Projetos", description: "Transformação de uma intenção em escopo, governança, orçamento, cronograma, indicadores e estratégia de recursos.", href: "/solucoes/estruturacao-de-projetos" },
    ],
    ctaLabel: "Converse sobre o desafio",
    ctaHref: "/contato",
  },

  "inteligencia-de-mercado": {
    eyebrow: "INTELIGÊNCIA DE MERCADO",
    title: "Decidir melhor começa por entender o mercado real.",
    intro: "Opiniões internas, tendências e dados isolados não formam uma estratégia. A inteligência de mercado conecta evidências para responder perguntas específicas sobre demanda, concorrência, públicos, contexto e oportunidade.",
    lead: "O trabalho começa pela decisão que precisa ser tomada. A pesquisa é desenhada para reduzir incerteza útil, não para acumular informação.",
    parentLabel: "Estratégia",
    parentHref: "/solucoes/estrategia",
    blocks: [
      { type: "bullets", heading: "Quando contratar Inteligência de Mercado", items: [
        "Antes de lançar um produto, serviço, programa ou evento.",
        "Ao entrar em um novo território, público ou segmento.",
        "Quando a concorrência mudou e a posição da organização perdeu clareza.",
        "Para avaliar uma oportunidade antes de investir recursos relevantes.",
        "Quando decisões internas estão baseadas em percepções conflitantes.",
        "Para compreender comportamento, necessidades e barreiras de um público.",
        "Antes de redefinir posicionamento, portfólio ou proposta de valor.",
      ]},
      { type: "cards", heading: "Escopo possível", items: [
        { title: "Pesquisa documental e dados secundários", description: "Levantamento de estudos, bases públicas, documentos, relatórios setoriais e informações disponíveis." },
        { title: "Benchmarking e concorrência", description: "Mapeamento de referências, ofertas, modelos de negócio, mensagens, experiências e movimentos competitivos." },
        { title: "Públicos e demanda", description: "Entrevistas, questionários, escuta qualitativa, análise de jornada e investigação de necessidades." },
        { title: "Tendências e cenários", description: "Identificação de forças de mudança, sinais emergentes, riscos e possíveis consequências para a decisão." },
        { title: "Contexto territorial", description: "Leitura de atores, infraestrutura, dinâmicas locais, oportunidades e restrições do território." },
        { title: "Síntese estratégica", description: "Organização das evidências em implicações, opções e recomendações práticas." },
      ]},
      { type: "bullets", heading: "O que você recebe", intro: "O formato depende da pergunta, mas pode incluir:", items: [
        "Plano de pesquisa.",
        "Mapa de mercado ou ecossistema.",
        "Análise de concorrentes e referências.",
        "Perfis ou segmentos de público.",
        "Síntese de entrevistas e pesquisa de campo.",
        "Tendências com implicações para o negócio.",
        "Cenários e critérios de decisão.",
        "Oportunidades priorizadas.",
        "Recomendações e próximos testes.",
        "Relatório e apresentação executiva.",
      ]},
      { type: "steps", heading: "Como conduzimos", items: [
        { number: "01", title: "Definição da decisão", description: "Alinhamos o que precisa ser decidido, por quem e em qual prazo." },
        { number: "02", title: "Desenho da pesquisa", description: "Escolhemos fontes, métodos, amostra, profundidade e critérios compatíveis com a decisão e o orçamento." },
        { number: "03", title: "Coleta e análise", description: "Reunimos dados, identificamos padrões e registramos limitações." },
        { number: "04", title: "Interpretação", description: "Traduzimos evidências em implicações, hipóteses e opções." },
        { number: "05", title: "Recomendação", description: "Apresentamos o que os dados permitem concluir, o que permanece incerto e quais passos reduzem o risco seguinte." },
      ]},
      { type: "bullets", heading: "Para quem", items: [
        "PMEs avaliando expansão ou nova oferta.",
        "Áreas de inovação, estratégia e marketing.",
        "Institutos e áreas de responsabilidade social.",
        "Creators e negócios da economia criativa.",
        "Agências e produtoras preparando projetos para clientes.",
        "Organizações que precisam entender um território antes de atuar.",
      ]},
    ],
    ctaLabel: "Apresente sua pergunta de negócio",
    ctaHref: "/contato",
  },

  "diagnostico-e-planejamento": {
    eyebrow: "DIAGNÓSTICO E PLANEJAMENTO",
    title: "Antes do plano, o problema certo.",
    intro: "Planejar cedo demais pode organizar a resposta errada. O diagnóstico esclarece o que está acontecendo, por que isso importa e quais condições precisam mudar.",
    lead: "O planejamento transforma essa leitura em prioridades, ações, responsáveis e critérios de acompanhamento.",
    parentLabel: "Estratégia",
    parentHref: "/solucoes/estrategia",
    blocks: [
      { type: "bullets", heading: "Sinais de que o diagnóstico é necessário", items: [
        "O pedido inicial descreve uma solução, mas o problema ainda não está claro.",
        "Cada área apresenta uma leitura diferente da situação.",
        "Existem iniciativas demais e prioridades de menos.",
        "O projeto perdeu ritmo e ninguém consegue apontar uma única causa.",
        "Metas foram definidas sem conexão com capacidade, recursos ou público.",
        "Uma mudança importante precisa ser implantada, mas ainda não existe plano compartilhado.",
      ]},
      { type: "steps", heading: "Do diagnóstico ao plano", items: [
        { number: "01", title: "Enquadramento", description: "Definimos a pergunta central, os públicos envolvidos e o uso esperado do trabalho." },
        { number: "02", title: "Escuta e coleta", description: "Analisamos documentos, dados e experiências das pessoas relevantes." },
        { number: "03", title: "Síntese", description: "Identificamos causas, padrões, tensões, lacunas e oportunidades." },
        { number: "04", title: "Priorização", description: "Comparamos temas por impacto, urgência, viabilidade e dependências." },
        { number: "05", title: "Planejamento", description: "Transformamos prioridades em objetivos, iniciativas, responsáveis, prazos, recursos e indicadores." },
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", items: [
        "Diagnóstico executivo.",
        "Mapa de causas e efeitos.",
        "Análise de stakeholders.",
        "Matriz de prioridades.",
        "Definição de objetivos e resultados esperados.",
        "Roadmap de implantação.",
        "Plano de ação com responsáveis e prazos.",
        "Mapa de riscos e dependências.",
        "Sistema inicial de indicadores.",
      ]},
      { type: "bullets", heading: "Aplicações frequentes", items: [
        "Planejamento de novos projetos.",
        "Revisão de iniciativas travadas.",
        "Preparação de programas de impacto.",
        "Organização de áreas ou frentes de trabalho.",
        "Planejamento de eventos e experiências complexas.",
        "Desenho de programas de inovação.",
      ]},
    ],
    ctaLabel: "Converse sobre o contexto",
    ctaHref: "/contato",
  },

  "estruturacao-de-projetos": {
    eyebrow: "ESTRUTURAÇÃO E VIABILIZAÇÃO DE PROJETOS",
    title: "Uma ideia só vira projeto quando consegue ser executada.",
    intro: "Estruturamos iniciativas para que possam ser compreendidas, decididas, financiadas, geridas e realizadas.",
    lead: "Isso significa transformar intenção em objetivos, escopo, entregas, governança, recursos, cronograma, riscos e indicadores coerentes entre si.",
    parentLabel: "Estratégia",
    parentHref: "/solucoes/estrategia",
    blocks: [
      { type: "bullets", heading: "Quando uma iniciativa ainda não é um projeto", items: [
        "Objetivos amplos sem entregas definidas.",
        "Público ou beneficiários descritos de forma genérica.",
        "Orçamento sem memória de cálculo.",
        "Cronograma sem dependências ou responsáveis.",
        "Parceiros citados, mas ainda não mobilizados.",
        "Indicadores que não podem ser medidos.",
        "Expectativa de captação sem estratégia de financiamento.",
      ]},
      { type: "cards", heading: "O que estruturamos", items: [
        { title: "Lógica do projeto", description: "Problema, justificativa, objetivos, públicos, resultados esperados e relação entre atividades e entregas." },
        { title: "Escopo e entregas", description: "O que será feito, o que ficará fora, como cada entrega será aceita e quais dependências existem." },
        { title: "Governança", description: "Papéis, responsabilidades, fóruns de decisão, parceiros e formas de acompanhamento." },
        { title: "Plano de realização", description: "Etapas, cronograma, equipe, fornecedores, recursos, riscos e operação necessária." },
        { title: "Orçamento", description: "Categorias de custo, premissas, cotações, reservas e relação entre recursos e atividades." },
        { title: "Indicadores", description: "Como acompanhar execução, alcance, qualidade, resultado e aprendizado." },
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", items: [
        "Documento estruturado do projeto.",
        "Matriz lógica ou teoria de mudança.",
        "Escopo e estrutura analítica do projeto.",
        "Plano de trabalho.",
        "Cronograma e marcos.",
        "Orçamento e memória de cálculo.",
        "Mapa de governança e stakeholders.",
        "Matriz de riscos.",
        "Plano de indicadores.",
        "Estratégia de parcerias e recursos.",
        "Apresentação institucional ou comercial.",
      ]},
      { type: "steps", heading: "Como trabalhamos", items: [
        { number: "01", title: "Entendimento", description: "Reunimos o que já existe e definimos as perguntas ainda sem resposta." },
        { number: "02", title: "Arquitetura", description: "Conectamos problema, objetivos, públicos, atividades, entregas e resultados." },
        { number: "03", title: "Modelagem", description: "Estruturamos governança, cronograma, recursos, orçamento, riscos e indicadores." },
        { number: "04", title: "Validação", description: "Testamos coerência, capacidade de execução e aderência ao processo decisório ou mecanismo de financiamento." },
        { number: "05", title: "Preparação", description: "Consolidamos documentos, apresentações e próximos passos para contratação, parceria ou implantação." },
      ]},
      { type: "bullets", heading: "Projetos que podemos estruturar", items: [
        "Iniciativas corporativas.",
        "Programas de inovação.",
        "Projetos culturais e de economia criativa.",
        "Programas de responsabilidade social.",
        "Eventos e experiências.",
        "Projetos territoriais.",
        "Iniciativas autorais.",
        "Projetos para contratação direta, patrocínio, editais ou leis de incentivo.",
      ]},
    ],
    ctaLabel: "Estruture seu projeto",
    ctaHref: "/contato",
  },

  gestao: {
    eyebrow: "GESTÃO",
    title: "A responsabilidade que não se transfere.",
    intro: "Um plano não cria ritmo sozinho. Projetos avançam quando decisões têm responsáveis, informações circulam, riscos são tratados e as equipes sabem o que precisa acontecer em seguida.",
    lead: "A Creation estrutura e conduz esse sistema de gestão, conectando estratégia, pessoas, processos e entregas.",
    parentLabel: "Soluções",
    parentHref: "/solucoes",
    blocks: [
      { type: "bullets", heading: "Quando a Gestão precisa entrar", items: [
        "O projeto atravessa áreas e não possui uma liderança de integração.",
        "Há muitas reuniões, mas poucas decisões registradas.",
        "Prazos mudam sem que os impactos sejam compreendidos.",
        "Equipes e fornecedores trabalham com versões diferentes do plano.",
        "O cliente possui conhecimento técnico, mas não capacidade disponível para coordenar tudo.",
        "Problemas recorrentes indicam falhas de processo, não apenas de esforço.",
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", items: [
        "Plano de projeto.",
        "Estrutura de governança.",
        "Matriz de responsabilidades.",
        "Cronograma integrado.",
        "Orçamento e controle de custos.",
        "Mapa de riscos, problemas e dependências.",
        "Plano de comunicação e stakeholders.",
        "Dashboards e relatórios executivos.",
        "Processos e procedimentos.",
        "Relatório de encerramento e lições aprendidas.",
      ]},
    ],
    childrenLabel: "O que podemos assumir",
    children: [
      { title: "Gestão de Projetos e PMO", description: "Planejamento, governança, coordenação, acompanhamento e encerramento de projetos ou portfólios.", href: "/solucoes/gestao-de-projetos" },
      { title: "Gestão de Processos de Negócios", description: "Mapeamento, redesenho e implantação de processos para reduzir dependência de pessoas, retrabalho e perda de informação.", href: "/solucoes/gestao-de-processos" },
      { title: "Governança e Indicadores", description: "Papéis, fóruns, critérios de decisão, indicadores e rotinas para transformar acompanhamento em ação.", href: "/solucoes/governanca-e-indicadores" },
    ],
    ctaLabel: "Converse sobre a gestão do projeto",
    ctaHref: "/contato",
  },

  "gestao-de-projetos": {
    eyebrow: "GESTÃO DE PROJETOS E PMO",
    title: "Projetos avançam quando decisões têm dono.",
    intro: "Coordenamos o sistema que conecta objetivo, escopo, equipes, orçamento, prazo, riscos e entregas.",
    lead: "A gestão transforma informação dispersa em decisões visíveis e mantém o trabalho em movimento até a conclusão.",
    parentLabel: "Gestão",
    parentHref: "/solucoes/gestao",
    blocks: [
      { type: "cards", heading: "Escopo possível", items: [
        { title: "Iniciação", description: "Objetivo, escopo, entregas, stakeholders, premissas, restrições e critérios de sucesso." },
        { title: "Planejamento", description: "Cronograma, orçamento, equipe, aquisições, comunicação, riscos, qualidade e indicadores." },
        { title: "Governança", description: "Papéis, fóruns, alçadas, cadência, registros e caminhos de escalonamento." },
        { title: "Coordenação", description: "Acompanhamento de equipes, parceiros, fornecedores, dependências e decisões." },
        { title: "Controle", description: "Monitoramento de prazo, custo, escopo, riscos, problemas, mudanças e entregas." },
        { title: "Encerramento", description: "Aceite, documentação, prestação de contas, lições aprendidas e transição." },
      ]},
      { type: "cards", heading: "PMO no tamanho que o contexto exige", intro: "PMO não precisa significar uma estrutura pesada ou permanente.", items: [
        { title: "PMO de projeto", description: "Organiza governança, informação e acompanhamento de uma iniciativa específica." },
        { title: "PMO de programa", description: "Coordena projetos relacionados, benefícios compartilhados e dependências entre frentes." },
        { title: "PMO de portfólio", description: "Apoia priorização, capacidade, indicadores e decisões sobre várias iniciativas." },
        { title: "PMO temporário", description: "Implanta práticas e opera a gestão durante uma fase crítica, preparando a transferência para a equipe interna." },
      ]},
      { type: "bullets", heading: "O que pode ser entregue", items: [
        "Termo de abertura ou documento de iniciação.",
        "Plano integrado do projeto.",
        "Estrutura analítica e cronograma.",
        "Matriz de responsabilidades.",
        "Orçamento e controle de compromissos.",
        "Mapa de stakeholders.",
        "Matriz de riscos e problemas.",
        "Dashboard executivo.",
        "Relatórios de status.",
        "Plano de encerramento e transição.",
      ]},
      { type: "bullets", heading: "A Creation pode entrar em três momentos", items: [
        "Antes do início — para estruturar o projeto e preparar governança, plano e mobilização.",
        "Durante a execução — para assumir a coordenação, recuperar visibilidade e tratar impedimentos.",
        "Em uma fase crítica — para reorganizar uma frente, preparar um evento, realizar uma implantação ou conduzir o encerramento.",
      ]},
      { type: "bullets", heading: "Para quem", items: [
        "PMEs sem estrutura interna dedicada de projetos.",
        "Áreas corporativas conduzindo iniciativas transversais.",
        "Institutos e organizações sociais.",
        "Agências e produtoras que precisam de coordenação adicional.",
        "Programas de inovação, impacto, eventos e economia criativa.",
      ]},
    ],
    ctaLabel: "Fale sobre seu projeto",
    ctaHref: "/contato",
  },

  "gestao-de-processos": {
    eyebrow: "GESTÃO DE PROCESSOS DE NEGÓCIOS",
    title: "O trabalho precisa funcionar além das pessoas que o sustentam.",
    intro: "Quando um processo existe apenas na memória de quem o executa, a organização fica vulnerável a atrasos, retrabalho, perda de informação e decisões inconsistentes.",
    lead: "Mapeamos como o trabalho acontece, redesenhamos o que precisa mudar e acompanhamos a implantação até que o novo fluxo possa ser operado pela equipe.",
    parentLabel: "Gestão",
    parentHref: "/solucoes/gestao",
    blocks: [
      { type: "bullets", heading: "Sinais de que o processo precisa ser revisto", items: [
        "A mesma tarefa é executada de maneiras diferentes.",
        "Informações precisam ser digitadas ou conferidas várias vezes.",
        "Aprovações não possuem prazo, critério ou responsável claro.",
        "O cliente ou usuário não sabe em que etapa está.",
        "A operação depende excessivamente de uma pessoa.",
        "Ferramentas foram implantadas sem redesenhar o fluxo de trabalho.",
      ]},
      { type: "steps", heading: "Como conduzimos", items: [
        { number: "01", title: "Priorizar", description: "Escolhemos os processos com maior efeito sobre resultado, risco ou experiência." },
        { number: "02", title: "Compreender", description: "Mapeamos o fluxo real, incluindo atalhos e exceções que raramente aparecem nos manuais." },
        { number: "03", title: "Redesenhar", description: "Construímos o processo futuro com participação de quem decide e de quem executa." },
        { number: "04", title: "Implantar", description: "Definimos responsáveis, procedimentos, ferramentas, treinamento e transição." },
        { number: "05", title: "Acompanhar", description: "Medimos adoção, corrigimos falhas e preparamos a operação autônoma." },
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", items: [
        "Inventário de processos.",
        "Mapas do estado atual e futuro.",
        "Diagramas BPMN quando adequados.",
        "Matriz de responsabilidades.",
        "Análise de gargalos e riscos.",
        "Procedimentos e instruções de trabalho.",
        "Critérios e alçadas de decisão.",
        "Requisitos funcionais para sistemas.",
        "Indicadores de processo.",
        "Plano de implantação.",
      ]},
      { type: "bullets", heading: "Aplicações frequentes", items: [
        "Atendimento e jornada do cliente.",
        "Elaboração e aprovação de propostas.",
        "Compras e gestão de fornecedores.",
        "Produção de eventos.",
        "Gestão de projetos.",
        "Operação de programas sociais.",
        "Criação e publicação de conteúdo.",
        "Prestação de contas.",
      ]},
    ],
    ctaLabel: "Converse sobre seus processos",
    ctaHref: "/contato",
  },

  "governanca-e-indicadores": {
    eyebrow: "GOVERNANÇA E INDICADORES",
    title: "Decisão, responsabilidade e evidência no mesmo sistema.",
    intro: "Governança define quem decide, com base em qual informação e dentro de que limite. Indicadores mostram o que precisa de atenção.",
    lead: "Quando os dois elementos estão desconectados, relatórios se acumulam e problemas continuam sem responsável. Estruturamos o sistema que liga informação a decisão e decisão a acompanhamento.",
    parentLabel: "Gestão",
    parentHref: "/solucoes/gestao",
    blocks: [
      { type: "cards", heading: "O que estruturamos", items: [
        { title: "Arquitetura de governança", description: "Papéis, responsabilidades, fóruns, alçadas, escalonamento e relação entre instâncias." },
        { title: "Matriz de decisão", description: "Quem recomenda, aprova, executa, consulta e acompanha cada tema relevante." },
        { title: "Cadência de gestão", description: "Reuniões, ritos, pautas, preparação, registros e acompanhamento de decisões." },
        { title: "Sistema de indicadores", description: "Objetivos, perguntas de gestão, métricas, fórmulas, fontes, periodicidade e responsáveis." },
        { title: "Dashboards e relatórios", description: "Visualizações e sínteses adequadas a quem opera, gere ou patrocina." },
        { title: "Prestação de contas", description: "Organização de evidências, entregas, resultados, riscos, desvios e aprendizados." },
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", items: [
        "Mapa de governança.",
        "Matriz RACI ou equivalente.",
        "Regimento de fóruns e comitês.",
        "Matriz de alçadas.",
        "Calendário de gestão.",
        "Árvore ou catálogo de indicadores.",
        "Fichas técnicas das métricas.",
        "Modelo de dashboard.",
        "Modelo de relatório executivo.",
        "Plano de implantação e adoção.",
      ]},
      { type: "bullets", heading: "Diferentes níveis de evidência", intro: "Distinguimos atividade, entrega, alcance, resultado e impacto — para que volume de atividade nunca seja apresentado como transformação comprovada.", items: [
        "Atividade: o que foi feito.",
        "Entrega: o que foi produzido.",
        "Alcance: quem foi envolvido.",
        "Resultado: o que mudou de forma observável.",
        "Impacto: mudança atribuível ou plausivelmente relacionada, conforme método e evidência disponíveis.",
      ]},
      { type: "bullets", heading: "Para projetos, programas e operações", items: [
        "Projetos corporativos.",
        "Programas de responsabilidade social.",
        "Portfólios e PMOs.",
        "Organizações sociais.",
        "Eventos e experiências.",
        "Processos recorrentes.",
        "Iniciativas de inovação.",
        "Parcerias com múltiplos stakeholders.",
      ]},
    ],
    ctaLabel: "Converse sobre sua governança",
    ctaHref: "/contato",
  },

  operacoes: {
    eyebrow: "OPERAÇÕES",
    title: "É na execução que o projeto se decide.",
    intro: "Um bom plano precisa funcionar no tempo, no orçamento e no território reais. A Creation coordena pessoas, fornecedores, recursos, licenças, deslocamentos e decisões para que cada frente avance com clareza até a entrega.",
    lead: "Atuamos como núcleo de operação ou como extensão da equipe do cliente, com responsabilidade definida e acompanhamento próximo.",
    parentLabel: "Soluções",
    parentHref: "/solucoes",
    blocks: [
      { type: "bullets", heading: "O que coordenamos", items: [
        "Escopo operacional e critérios de entrega.",
        "Orçamento, contratações e controle de custos.",
        "Cronograma, marcos e sequenciamento.",
        "Fornecedores, equipes técnicas e parceiros.",
        "Infraestrutura, equipamentos e materiais.",
        "Licenças, autorizações e requisitos locais.",
        "Logística de pessoas, cargas e recursos.",
        "Contingências, mudanças e comunicação de campo.",
      ]},
      { type: "bullets", heading: "Onde entramos", intro: "A Creation pode assumir toda a operação ou uma frente delimitada. Também pode integrar estruturas já existentes, incluindo:", items: [
        "Equipes de marketing e comunicação.",
        "Produtoras e agências.",
        "Áreas de responsabilidade social e sustentabilidade.",
        "Organizações culturais e sociais.",
        "Produtoras audiovisuais.",
        "Marcas, creators e projetos independentes.",
      ]},
    ],
    childrenLabel: "Nossas frentes de atuação",
    children: [
      { title: "Gestão de Eventos", description: "Planejamento e coordenação do ciclo completo de eventos corporativos, culturais, institucionais, de inovação e de impacto.", href: "/operacoes/gestao-de-eventos" },
      { title: "Produção Executiva", description: "Orçamento, cronograma, fornecedores, equipes, infraestrutura e acompanhamento da realização, da pré-produção ao encerramento.", href: "/operacoes/producao-executiva" },
      { title: "Location & Fixer", description: "Pesquisa de locações, articulação local, licenças, apoio a equipes e solução de necessidades de produção no Rio de Janeiro e na Costa Verde.", href: "/operacoes/location-fixer-rio-de-janeiro" },
      { title: "Receptivo, Drivers & Locações", description: "Deslocamentos, veículos, motoristas, hospedagem, espaços, equipamentos e suporte de chegada para equipes, convidados e produções.", href: "/operacoes/receptivo-drivers-locacoes" },
    ],
    ctaLabel: "Apresente sua operação",
    ctaHref: "/contato",
  },

  "gestao-de-eventos": {
    eyebrow: "GESTÃO DE EVENTOS",
    title: "Um evento começa muito antes da montagem.",
    intro: "Objetivo, público, experiência, conteúdo, orçamento e operação precisam apontar para a mesma direção.",
    lead: "A Creation estrutura e coordena eventos do conceito ao encerramento, conectando decisão estratégica e realização.",
    parentLabel: "Operações",
    parentHref: "/operacoes",
    blocks: [
      { type: "steps", heading: "O ciclo completo", items: [
        { number: "01", title: "Conceito e objetivos", description: "Definição do papel do evento, públicos, proposta de valor, resultados esperados e critérios de sucesso." },
        { number: "02", title: "Arquitetura da experiência", description: "Formato, programação, jornada do participante, ambientes, fluxos, ativações e pontos de contato." },
        { number: "03", title: "Planejamento", description: "Escopo, orçamento, cronograma, governança, fornecedores, riscos, licenças e plano operacional." },
        { number: "04", title: "Produção", description: "Infraestrutura, audiovisual, cenografia, alimentação, equipes, materiais, logística, montagem e testes." },
        { number: "05", title: "Realização e encerramento", description: "Coordenação geral, operação de sala ou palco, desmontagem, conferência, dados e relatório." },
      ]},
      { type: "bullets", heading: "Eventos que podemos estruturar e realizar", items: [
        "Encontros corporativos e institucionais.",
        "Conferências, fóruns e seminários.",
        "Hackathons e programas de inovação.",
        "Eventos culturais e de economia criativa.",
        "Ativações de marca e live marketing.",
        "Eventos de responsabilidade social e impacto.",
        "Transmissões ao vivo e formatos híbridos.",
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", items: [
        "Conceito e desenho do evento.",
        "Plano mestre e cronograma.",
        "Orçamento e mapa de contratações.",
        "Matriz de responsabilidades.",
        "Programação e roteiro técnico.",
        "Plano de espaços, fluxos e acessos.",
        "Plano de riscos e contingências.",
        "Operação de credenciamento.",
        "Relatório de execução e indicadores.",
      ]},
    ],
    ctaLabel: "Planeje seu evento",
    ctaHref: "/contato",
  },

  "producao-executiva": {
    eyebrow: "PRODUÇÃO EXECUTIVA",
    title: "Produção executiva é transformar muitas dependências em uma entrega.",
    intro: "Quando o projeto precisa sair do papel, cada contratação, prazo, acesso e decisão passa a afetar o conjunto.",
    lead: "A Creation organiza essas dependências e coordena a realização com visão de orçamento, cronograma, qualidade e risco.",
    parentLabel: "Operações",
    parentHref: "/operacoes",
    blocks: [
      { type: "bullets", heading: "Onde atuamos", items: [
        "Eventos corporativos, culturais e institucionais.",
        "Campanhas e ativações de marca.",
        "Projetos de inovação e economia criativa.",
        "Programas sociais e territoriais.",
        "Gravações, conteúdos e produções audiovisuais.",
        "Feiras, exposições e experiências.",
        "Projetos especiais com múltiplos parceiros.",
      ]},
      { type: "cards", heading: "O que a produção executiva pode incluir", items: [
        { title: "Planejamento de produção", description: "Decomposição do escopo, cronograma, orçamento, mapa de recursos, sequência de trabalho e pontos de decisão." },
        { title: "Orçamentos e contratações", description: "Solicitação e comparação de propostas, equalização técnica e comercial, apoio à contratação e controle de compromissos." },
        { title: "Fornecedores e equipes", description: "Seleção, briefing, integração, acompanhamento, validação de entregas e gestão das interfaces." },
        { title: "Infraestrutura e logística", description: "Espaços, equipamentos, materiais, transportes, hospedagem, alimentação, acessos, cargas e devoluções." },
        { title: "Licenças e requisitos", description: "Mapeamento de autorizações, documentos, seguros e responsabilidades técnicas aplicáveis." },
        { title: "Operação de campo", description: "Montagem, testes, passagem, realização, desmontagem, controle de ocorrências e comunicação entre as frentes." },
      ]},
      { type: "bullets", heading: "Controles que sustentam a entrega", items: [
        "Orçamento-base e projeção de fechamento.",
        "Cronograma de produção.",
        "Mapa de fornecedores e contratos.",
        "Matriz de responsabilidades.",
        "Controle de aprovações e mudanças.",
        "Lista de equipamentos e materiais.",
        "Plano de acessos e credenciamento.",
        "Mapa de riscos e contingências.",
        "Relatório de ocorrências e encerramento.",
      ]},
      { type: "bullets", heading: "Como nos integramos à equipe", items: [
        "Produção completa — a Creation responde pelo planejamento e pela coordenação do conjunto definido em contrato.",
        "Frente específica — assumimos uma parte delimitada, como logística, fornecedores, produção local ou operação de campo.",
        "Reforço temporário — entramos como extensão da agência, produtora, marca ou organização durante uma etapa crítica.",
      ]},
    ],
    ctaLabel: "Converse sobre sua produção",
    ctaHref: "/contato",
  },

  "location-fixer-rio-de-janeiro": {
    eyebrow: "LOCATION & FIXER",
    title: "Você chega com o projeto. A operação local já sabe o caminho.",
    intro: "Locações, autorizações, acessos, equipes e deslocamentos mudam de um território para outro.",
    lead: "A Creation oferece pesquisa de locações e suporte de produção local para equipes que precisam realizar filmagens, campanhas, eventos e projetos no Rio de Janeiro e na Costa Verde.",
    parentLabel: "Operações",
    parentHref: "/operacoes",
    blocks: [
      { type: "cards", heading: "Dois serviços que se complementam", items: [
        { title: "Location", description: "Pesquisa e viabilização de espaços compatíveis com a proposta criativa, as necessidades técnicas, o orçamento e a logística da produção." },
        { title: "Fixer", description: "Articulação local para transformar o briefing em uma operação possível, conectando informações, pessoas, fornecedores, requisitos e decisões no território." },
      ]},
      { type: "bullets", heading: "Serviços de location", items: [
        "Leitura do briefing criativo e técnico.",
        "Pesquisa inicial de opções.",
        "Scouting presencial, conforme escopo.",
        "Fotos, vídeos e informações operacionais.",
        "Análise de acesso, ruído, energia, apoio e circulação.",
        "Interface com proprietários, administradores e órgãos responsáveis.",
        "Apoio à negociação e documentação.",
        "Coordenação de visitas técnicas.",
      ]},
      { type: "bullets", heading: "Serviços de fixer", items: [
        "Pesquisa local e levantamento de informações.",
        "Indicação e coordenação de fornecedores.",
        "Articulação com comunidades, instituições e agentes locais.",
        "Apoio a licenças, autorizações e documentos.",
        "Contratação de equipes e recursos, conforme modelo definido.",
        "Produção de campo e acompanhamento de agenda.",
        "Tradução cultural e orientação operacional.",
        "Logística, segurança e planos de deslocamento.",
      ]},
      { type: "bullets", heading: "Para quais projetos", items: [
        "Publicidade e campanhas de marca.",
        "Cinema, séries, documentários e televisão.",
        "Fotografia e conteúdo digital.",
        "Creators e equipes internacionais.",
        "Eventos, experiências e ativações.",
        "Pesquisa de campo e projetos institucionais.",
      ]},
    ],
    ctaLabel: "Envie seu briefing",
    ctaHref: "/contato",
  },

  "receptivo-drivers-locacoes": {
    eyebrow: "RECEPTIVO, DRIVERS & LOCAÇÕES",
    title: "A logística começa antes da chegada.",
    intro: "Equipes, convidados e recursos precisam estar no lugar certo, no horário certo e com informação suficiente para seguir o plano.",
    lead: "A Creation coordena a logística de chegada, permanência e deslocamento para produções, eventos e projetos especiais.",
    parentLabel: "Operações",
    parentHref: "/operacoes",
    blocks: [
      { type: "cards", heading: "O que podemos coordenar", items: [
        { title: "Chegadas e partidas", description: "Recepção em aeroportos, rodoviárias, hotéis, bases de produção e outros pontos definidos." },
        { title: "Transfers e drivers", description: "Motoristas, veículos executivos, vans, ônibus, utilitários e outros recursos compatíveis com o deslocamento." },
        { title: "Rotas e agendas", description: "Planejamento de trajetos, janelas de saída, pontos de encontro, tempo de margem e atualizações operacionais." },
        { title: "Hospedagem e bases", description: "Pesquisa e coordenação de hotéis, casas, apartamentos, salas de apoio, camarins e bases operacionais." },
        { title: "Locações de recursos", description: "Veículos, equipamentos, mobiliário, estruturas, comunicação, apoio e outros itens previstos no escopo." },
        { title: "Suporte de permanência", description: "Informações de serviço, acompanhamento de convidados, apoio de produção e solução de necessidades durante a agenda." },
      ]},
      { type: "bullets", heading: "Para quem", items: [
        "Equipes de filmagem e fotografia.",
        "Convidados, palestrantes e executivos.",
        "Artistas, creators e influenciadores.",
        "Equipes de marcas, agências e produtoras.",
        "Delegações e grupos institucionais.",
        "Equipes técnicas e fornecedores.",
      ]},
      { type: "bullets", heading: "Informações que organizamos", items: [
        "Nomes, contatos e responsáveis.",
        "Voos, horários e pontos de chegada.",
        "Hospedagens e endereços.",
        "Agenda consolidada.",
        "Veículos, capacidade e bagagens.",
        "Credenciais, acessos e autorizações.",
        "Contatos de emergência e escalonamento.",
        "Plano alternativo para atrasos e mudanças.",
      ]},
    ],
    ctaLabel: "Planeje sua logística",
    ctaHref: "/contato",
  },

  inovacao: {
    eyebrow: "INOVAÇÃO",
    title: "Ideias ganham valor quando se tornam projetos.",
    intro: "Inovação não começa em uma dinâmica e não termina em uma apresentação. Ela precisa de um problema relevante, critérios de decisão, pessoas mobilizadas e um caminho para testar, aprender e implementar.",
    lead: "A Creation estrutura e realiza iniciativas de inovação conectadas à estratégia e à capacidade real da organização.",
    image: { src: "/images/hacking-rio.webp", alt: "Hacking.Rio — programa de inovação realizado pela Creation" },
    parentLabel: "Soluções",
    parentHref: "/solucoes",
    blocks: [
      { type: "cards", heading: "Frentes de atuação", items: [
        { title: "Estratégia de inovação", description: "Leitura de contexto, definição de temas prioritários, objetivos, portfólio, governança e indicadores." },
        { title: "Desenho de desafios", description: "Formulação do problema, perguntas orientadoras, critérios, públicos, dados e condições de participação." },
        { title: "Programas e jornadas", description: "Estruturação de hackathons, laboratórios, sprints, chamadas, ciclos de ideação, aceleração e inovação aberta." },
        { title: "Facilitação e conteúdo", description: "Oficinas, encontros, mentorias, curadoria, materiais e condução de processos colaborativos." },
        { title: "Experimentação", description: "Hipóteses, protótipos, planos de teste, critérios de validação e registro de aprendizados." },
        { title: "Implantação", description: "Transformação das soluções selecionadas em projetos, com responsáveis, recursos, cronograma e governança." },
      ]},
      { type: "bullets", heading: "Perguntas que organizam um programa", items: [
        "Qual problema precisa ser resolvido e por que agora?",
        "O que já se sabe e o que ainda precisa ser investigado?",
        "Quem vive o problema e quem pode decidir sobre a solução?",
        "Que restrições não podem ser ignoradas?",
        "Como as propostas serão comparadas?",
        "Que recursos existirão para testar e implementar?",
        "Quem assume a continuidade depois do programa?",
      ]},
      { type: "steps", heading: "Como trabalhamos", items: [
        { number: "01", title: "Investigar", description: "Contexto, problema, públicos, restrições e evidências." },
        { number: "02", title: "Desenhar", description: "Formato, jornada, governança, critérios, recursos e comunicação." },
        { number: "03", title: "Mobilizar", description: "Participantes, especialistas, parceiros, mentores e decisores." },
        { number: "04", title: "Realizar", description: "Conteúdo, facilitação, operação, registro e acompanhamento." },
        { number: "05", title: "Desdobrar", description: "Seleção, pilotos, projetos, aprendizados e próximos passos." },
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", items: [
        "Diagnóstico de inovação.",
        "Tese ou agenda de prioridades.",
        "Mapa de oportunidades.",
        "Arquitetura de programa.",
        "Regulamento e critérios de seleção.",
        "Plano de mobilização.",
        "Jornada de participantes.",
        "Backlog de hipóteses e experimentos.",
        "Plano de pilotos.",
        "Modelo de governança.",
        "Relatório de resultados e recomendações.",
      ]},
    ],
    ctaLabel: "Converse sobre seu desafio",
    ctaHref: "/contato",
  },

  impacto: {
    eyebrow: "IMPACTO",
    title: "Impacto que se constrói e se comprova.",
    intro: "Intenção social não substitui estratégia, gestão nem evidência. A Creation ajuda empresas, organizações e parceiros a transformar compromissos em programas estruturados.",
    lead: "Com públicos definidos, responsabilidades claras e acompanhamento compatível com o que se pretende mudar.",
    image: { src: "/images/impacto-hero.jpg", alt: "Programa de impacto social em território, realizado pela Creation" },
    parentLabel: "Soluções",
    parentHref: "/solucoes",
    blocks: [
      { type: "cards", heading: "Frentes de atuação", items: [
        { title: "Diagnóstico social e territorial", description: "Leitura de contexto, públicos, ativos, vulnerabilidades, atores, iniciativas existentes, dados e lacunas de conhecimento." },
        { title: "Estratégia de impacto", description: "Definição de prioridades, públicos, objetivos, princípios, critérios e relação com a estratégia da organização." },
        { title: "Teoria da mudança", description: "Organização das relações esperadas entre recursos, atividades, entregas, resultados e impactos, incluindo premissas e fatores externos." },
        { title: "Desenho de programas", description: "Escopo, jornada dos participantes, parceiros, governança, orçamento, cronograma, riscos e indicadores." },
        { title: "Gestão e operação", description: "Coordenação de equipes, parceiros, territórios, fornecedores, decisões e entregas." },
        { title: "Monitoramento e avaliação", description: "Perguntas avaliativas, indicadores, fontes, instrumentos, análise, limitações e comunicação de resultados." },
      ]},
      { type: "bullets", heading: "O que diferenciamos", intro: "Essa distinção reduz o risco de comunicar volume de execução como se fosse transformação comprovada.", items: [
        "Insumo: recurso utilizado.",
        "Atividade: ação realizada.",
        "Entrega: produto ou serviço disponibilizado.",
        "Alcance: pessoas ou organizações envolvidas.",
        "Resultado: mudança observada no público ou sistema.",
        "Impacto: mudança de maior alcance ou duração, analisada com atenção à contribuição, à atribuição e ao contexto.",
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", items: [
        "Diagnóstico ou linha de base.",
        "Mapa de stakeholders.",
        "Estratégia de atuação.",
        "Teoria da mudança.",
        "Desenho de programa.",
        "Matriz lógica.",
        "Plano de implementação.",
        "Modelo de governança.",
        "Matriz de riscos.",
        "Plano de monitoramento e avaliação.",
        "Catálogo de indicadores.",
        "Painel ou relatório.",
        "Avaliação de resultados.",
      ]},
    ],
    childrenLabel: "Especialidade relacionada",
    children: [
      { title: "Marketing de Causa", description: "Estratégia que conecta marca, causa e ação, com parceria, governança, experiência e comunicação responsável.", href: "/impacto/marketing-de-causa" },
    ],
    ctaLabel: "Converse sobre sua iniciativa",
    ctaHref: "/contato",
  },

  "marketing-de-causa": {
    eyebrow: "MARKETING DE CAUSA",
    title: "Uma causa não pode ser apenas uma campanha.",
    intro: "Quando uma marca se associa a uma questão social, assume responsabilidade sobre o que promete, como atua e quem envolve.",
    lead: "A Creation estrutura iniciativas que conectam posicionamento, parceria, experiência e entrega concreta.",
    parentLabel: "Impacto",
    parentHref: "/impacto",
    blocks: [
      { type: "cards", heading: "O que estruturamos", items: [
        { title: "Aderência entre marca e causa", description: "Análise de história, valores, atuação, públicos, riscos e contribuição possível." },
        { title: "Estratégia da iniciativa", description: "Objetivo, públicos, proposta, tese de atuação, resultados esperados e critérios de decisão." },
        { title: "Mapeamento e parceria", description: "Identificação, avaliação e construção da relação com organizações, especialistas, territórios e redes." },
        { title: "Conceito e experiência", description: "Tradução da estratégia em programa, campanha, conteúdo, evento, ativação ou jornada de engajamento." },
        { title: "Governança", description: "Papéis, aprovações, uso de imagem, recursos, integridade, acompanhamento e resposta a riscos." },
        { title: "Realização e evidência", description: "Produção, gestão, indicadores, registros, prestação de contas e aprendizados." },
      ]},
      { type: "bullets", heading: "Formatos possíveis", items: [
        "Campanhas vinculadas a uma ação concreta.",
        "Programas de engajamento de clientes ou colaboradores.",
        "Ativações e experiências com propósito.",
        "Eventos, encontros e mobilizações.",
        "Produtos ou edições especiais.",
        "Doações associadas a vendas, com regras transparentes.",
        "Plataformas de conteúdo e educação.",
        "Parcerias territoriais.",
      ]},
      { type: "bullets", heading: "Perguntas que precisam ser respondidas", items: [
        "Por que essa marca deve atuar nessa causa?",
        "Qual necessidade concreta será enfrentada?",
        "Quem participa das decisões?",
        "Que organização possui legitimidade e capacidade no tema?",
        "O que será entregue, para quem e em qual período?",
        "O que acontece quando a campanha termina?",
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", items: [
        "Análise de aderência e risco.",
        "Mapa de causas e oportunidades.",
        "Estratégia e narrativa central.",
        "Mapa de stakeholders.",
        "Critérios para seleção de parceiros.",
        "Desenho de programa ou campanha.",
        "Modelo de governança.",
        "Plano de mobilização e conteúdo.",
        "Matriz de indicadores.",
        "Protocolo de transparência.",
      ]},
    ],
    ctaLabel: "Converse sobre sua iniciativa",
    ctaHref: "/contato",
  },

  "branding-experiencias": {
    eyebrow: "BRANDING & EXPERIÊNCIAS",
    title: "Estratégia que pode ser vista, vivida e lembrada.",
    intro: "Uma marca se torna concreta nos encontros que produz. A Creation conecta posicionamento, conceito e operação para criar experiências coerentes com o que a organização quer representar.",
    lead: "E capazes de funcionar no mundo real.",
    image: { src: "/images/reservax-lounge.jpg", alt: "Ativação de marca ReservaX Lounge, realizada pela Creation" },
    parentLabel: "Soluções",
    parentHref: "/solucoes",
    blocks: [
      { type: "cards", heading: "Frentes de atuação", items: [
        { title: "Estratégia de marca", description: "Posicionamento, proposta de valor, públicos, mensagens, territórios de expressão e critérios de coerência." },
        { title: "Conceito criativo", description: "Ideia central, narrativa, linguagem, experiência e desdobramentos possíveis." },
        { title: "Experiência de marca", description: "Jornada, pontos de contato, interações, ambientes, conteúdo, serviços e comportamento da equipe." },
        { title: "Ativações e live marketing", description: "Desenho e realização de ações presenciais, híbridas ou itinerantes." },
        { title: "Eventos e encontros", description: "Formatos proprietários, lançamentos, comunidades, experiências para públicos internos e externos." },
        { title: "Conteúdo e parcerias", description: "Curadoria, creators, especialistas, organizações, territórios e redes compatíveis com a proposta." },
      ]},
      { type: "bullets", heading: "Experiências que podem ser estruturadas", items: [
        "Ativações de marca.",
        "Lançamentos e encontros proprietários.",
        "Experiências culturais.",
        "Ações de relacionamento.",
        "Programas para comunidades.",
        "Feiras, mostras e espaços de marca.",
        "Experiências para colaboradores.",
        "Campanhas com presença territorial.",
      ]},
      { type: "bullets", heading: "O que precisa permanecer coerente", items: [
        "Promessa — o que a marca afirma e qual expectativa cria.",
        "Participação — o que o público pode fazer, sentir, aprender ou levar consigo.",
        "Operação — como espaço, equipe, fila, acesso, conteúdo, atendimento e tecnologia sustentam a experiência.",
        "Continuidade — o que acontece depois do encontro e como a relação pode prosseguir.",
      ]},
      { type: "bullets", heading: "Entregáveis possíveis", items: [
        "Diagnóstico de marca e contexto.",
        "Posicionamento ou plataforma de mensagens.",
        "Conceito e narrativa da experiência.",
        "Arquitetura de jornada.",
        "Plano de pontos de contato.",
        "Briefing criativo e de produção.",
        "Curadoria de conteúdo e parceiros.",
        "Plano de ativação.",
        "Orçamento e cronograma.",
        "Indicadores e relatório.",
      ]},
    ],
    ctaLabel: "Converse sobre sua marca",
    ctaHref: "/contato",
  },

  "como-trabalhamos": {
    eyebrow: "COMO TRABALHAMOS",
    title: "Entender. Estruturar. Realizar. Comprovar.",
    intro: "Projetos diferentes exigem equipes, ferramentas e percursos diferentes. O que permanece é uma forma disciplinada de transformar uma necessidade em direção, estrutura, entrega e evidência.",
    lead: "Não chamamos essa abordagem de metodologia proprietária. O valor está em escolher e aplicar o método adequado a cada decisão, não em inventar nomes para etapas conhecidas.",
    blocks: [
      { type: "bullets", heading: "O percurso não precisa começar no início", items: [
        "Um desafio ainda difuso pode começar por Entender.",
        "Uma iniciativa aprovada pode começar por Estruturar.",
        "Um projeto planejado pode precisar de Realizar.",
        "Uma entrega concluída pode precisar de Comprovar.",
      ]},
      { type: "bullets", heading: "Responsabilidades claras antes da execução", intro: "Cada proposta deve definir:", items: [
        "O que a Creation assume.",
        "O que permanece com o cliente.",
        "Quais decisões dependem de terceiros.",
        "Quais entregas serão produzidas.",
        "Como mudanças serão aprovadas.",
        "Quando o trabalho estará concluído.",
      ]},
      { type: "bullets", heading: "Ferramentas a serviço do projeto", intro: "SWOT, PESTEL, BPMN, Canvas, Design Thinking, Lean, Kanban, Scrum, RACI, OKRs e outras ferramentas podem ser utilizadas quando ajudam a responder uma pergunta real. Não aplicamos uma ferramenta porque ela é conhecida — escolhemos o recurso pelo problema, pela maturidade da equipe e pela decisão que precisa ser tomada.", items: ["SWOT e PESTEL", "BPMN e Canvas", "Design Thinking e Lean", "Kanban e Scrum", "RACI e OKRs"] },
    ],
    childrenLabel: "As quatro etapas",
    children: [
      { title: "01 — Entender", description: "Investigamos o contexto, os públicos envolvidos, as necessidades, as restrições e o resultado esperado antes de propor uma solução.", href: "/contato" },
      { title: "02 — Estruturar", description: "Transformamos o entendimento em escopo, prioridades, governança, equipe, orçamento, cronograma, riscos e indicadores.", href: "/contato" },
      { title: "03 — Realizar", description: "Mobilizamos pessoas, parceiros e recursos, coordenamos decisões e conduzimos a execução do projeto até a entrega.", href: "/contato" },
      { title: "04 — Comprovar", description: "Monitoramos, documentamos e analisamos os resultados para demonstrar as entregas, avaliar o valor gerado e orientar os próximos passos.", href: "/contato" },
    ],
    ctaLabel: "Conte seu projeto",
    ctaHref: "/contato",
  },
};

export const homeCapacidades: HomeCapacidade[] = [
  {
    title: "Estratégia",
    tagline: "Clareza para decidir.",
    description: "Investigamos o contexto, organizamos informações e transformamos complexidade em direção.",
    items: ["Inteligência de Mercado", "Diagnóstico e Planejamento", "Estruturação e Viabilização de Projetos"],
    href: "/solucoes/estrategia",
    linkLabel: "Conheça Estratégia",
  },
  {
    title: "Gestão",
    tagline: "Ritmo para avançar.",
    description: "Transformamos direção em escopo, responsabilidades e decisões, com governança, equipes, processos e indicadores.",
    items: ["Gestão de Projetos e PMO", "Gestão de Processos de Negócio", "Governança, Indicadores e Riscos"],
    href: "/solucoes/gestao",
    linkLabel: "Conheça Gestão",
  },
  {
    title: "Operações",
    tagline: "Execução para realizar.",
    description: "Mobilizamos pessoas, parceiros, fornecedores, logística, espaços e recursos para transformar planejamento em entrega.",
    items: ["Gestão e Produção de Eventos", "Produção Executiva e Logística", "Location & Fixer", "Receptivo, Drivers e Locações"],
    href: "/operacoes",
    linkLabel: "Conheça Operações",
  },
];

export const homeEspecialidades: HomeEspecialidade[] = [
  {
    title: "Inovação",
    tagline: "Ideias ganham valor quando se tornam projetos.",
    description: "Estruturamos e realizamos programas de inovação, desafios, hackathons, ideathons e jornadas.",
    href: "/inovacao",
    linkLabel: "Conheça Inovação",
    image: { src: "/images/hacking-rio.webp", alt: "Hacking.Rio — programa de inovação realizado pela Creation" },
  },
  {
    title: "Impacto",
    tagline: "Impacto que se constrói e se comprova.",
    description: "Desenhamos, gerimos e realizamos programas de responsabilidade social, marketing de causa e desenvolvimento territorial.",
    href: "/impacto",
    linkLabel: "Conheça Impacto",
    image: { src: "/images/impacto-hero.jpg", alt: "Programa de impacto social em território, realizado pela Creation" },
  },
  {
    title: "Branding & Experiências",
    tagline: "Estratégia que pode ser vista, vivida e lembrada.",
    description: "Transformamos posicionamento em identidade, narrativa, conteúdo, ativações e experiências.",
    href: "/branding-experiencias",
    linkLabel: "Conheça Branding & Experiências",
    image: { src: "/images/reservax-lounge.jpg", alt: "Ativação de marca ReservaX Lounge, realizada pela Creation" },
  },
];

export const homeSolucoes: HomeSolucao[] = [
  {
    title: "Creation Ops Rio",
    description: "Operação local integrada para agências, produtoras, marcas e equipes que realizam projetos no Rio de Janeiro. Location, fixer, receptivo, drivers, locações, fornecedores e logística sob uma única coordenação.",
    href: "/creator-ops-rio",
  },
];

export const casesStub: CaseStub[] = [
  {
    title: "Hacking.Rio",
    client: "Íons Innovation",
    context: "Produção e operação executiva de quatro edições em três formatos diferentes (presencial, digital e metaverso), integrando participantes, mentores, parceiros e fornecedores.",
    numbers: ["4 edições", "3 formatos", "+5 mil competidores", "+170 mil pessoas alcançadas"],
  },
  {
    title: "Hacking.Help",
    client: "Íons Innovation",
    context: "Concepção e produção executiva de uma maratona on-line criada rapidamente para manter a mobilização de propósito social durante a pandemia.",
    numbers: ["1.533 competidores", "5 países de língua portuguesa", "R$ 500 mil em mídia espontânea estimada"],
  },
  {
    title: "HR Talks",
    client: "Íons Innovation",
    context: "Produção executiva de uma programação digital internacional de longa duração, coordenando agenda, palestrantes e transmissão ao vivo.",
    numbers: ["15.500 inscritos", "172 palestrantes globais", "40 horas de conteúdo ao vivo"],
  },
  {
    title: "Pertinho de Casa — Escola e Feiras",
    client: "Rede Asta e Porto Sudeste",
    context: "Coordenação territorial de uma escola de negócios e feiras de comercialização para fortalecer empreendedores locais.",
    numbers: ["2 frentes de atuação", "6 eventos de comercialização", "R$ 19.649 em vendas acompanhadas"],
  },
  {
    title: "Pertinho de Casa — Plataforma",
    client: "Rede Asta e Porto Sudeste",
    context: "Recrutamento de vendedores, articulação do Comitê pela Economia Local e acompanhamento trimestral da plataforma.",
    numbers: ["241 empreendedores", "56 bairros de Itaguaí e Seropédica", "R$ 30.650,11 em faturamento registrado"],
  },
  {
    title: "World Creativity Day",
    client: "Centro Cultural Banco do Brasil Rio de Janeiro",
    context: "Concepção e execução de programação presencial e on-line sobre criatividade, distribuída por espaços e dias diferentes.",
    numbers: ["3 dias de programação", "2 espaços", "+1 mil pessoas alcançadas", "+50 inspiradores on-line"],
  },
];
